import { DEFAULT_THEME } from '../ir/theme';
import type { CredentialTemplate } from '../ir/types';

export const classicTemplate: CredentialTemplate = {
    version: 1,
    name: 'Classic Card',
    size: { w: 360, h: 560 },
    theme: DEFAULT_THEME,
    elements: [
        {
            id: 'bg',
            type: 'rect',
            x: 12,
            y: 12,
            w: 336,
            h: 536,
            rx: 24,
            fill: { kind: 'solid', color: '$surface' },
        },
        {
            id: 'top-band',
            type: 'rect',
            x: 12,
            y: 12,
            w: 336,
            h: 152,
            rx: 24,
            fill: {
                kind: 'linear-gradient',
                from: '$primary',
                to: '$secondary',
                direction: 'horizontal',
            },
        },
        {
            id: 'header-label',
            type: 'text',
            x: 34,
            y: 48,
            content: { kind: 'static', value: 'LEARNCARD' },
            font: 'heading',
            size: 12,
            weight: 700,
            color: '$surface',
            align: 'start',
            letterSpacing: 1.6,
        },
        {
            id: 'accent-bar',
            type: 'rect',
            x: 34,
            y: 62,
            w: 84,
            h: 4,
            rx: 2,
            fill: { kind: 'solid', color: '$accent' },
        },
        {
            id: 'avatar-bg',
            type: 'rect',
            x: 118,
            y: 88,
            w: 124,
            h: 124,
            rx: 28,
            fill: { kind: 'solid', color: '$background' },
        },
        {
            id: 'avatar',
            type: 'image',
            x: 118,
            y: 88,
            w: 124,
            h: 124,
            source: { kind: 'binding', path: 'credentialSubject.achievement.image' },
            fit: 'cover',
            clip: 'rounded',
            cornerRadius: 28,
        },
        {
            id: 'title',
            type: 'text',
            x: 180,
            y: 258,
            content: {
                kind: 'binding',
                path: 'credentialSubject.achievement.name',
                fallback: 'Untitled Achievement',
            },
            font: 'heading',
            size: 24,
            weight: 700,
            color: '$text',
            align: 'middle',
        },
        {
            id: 'subtitle',
            type: 'text',
            x: 180,
            y: 282,
            content: {
                kind: 'binding',
                path: 'credentialSubject.achievement.achievementType',
            },
            font: 'body',
            size: 12,
            weight: 700,
            color: '$muted',
            align: 'middle',
            letterSpacing: 0.8,
            visibility: { kind: 'whenPresent', path: 'credentialSubject.achievement.achievementType' },
        },
        {
            id: 'divider',
            type: 'divider',
            x: 34,
            y: 340,
            w: 292,
            color: '$border',
            thickness: 1,
        },
        {
            id: 'subject-row',
            type: 'field-row',
            x: 34,
            y: 370,
            w: 292,
            label: 'ISSUED TO',
            value: {
                kind: 'binding',
                path: 'credentialSubject.name',
                fallback: 'Recipient',
            },
            labelColor: '$muted',
            valueColor: '$text',
        },
        {
            id: 'issuer-row',
            type: 'field-row',
            x: 34,
            y: 404,
            w: 292,
            label: 'ISSUED BY',
            value: {
                kind: 'binding',
                path: 'issuer.name',
                fallback: 'Issuer',
            },
            labelColor: '$muted',
            valueColor: '$text',
        },
        {
            id: 'date-row',
            type: 'field-row',
            x: 34,
            y: 438,
            w: 292,
            label: 'VALID FROM',
            value: { kind: 'binding', path: 'validFrom', format: 'long' },
            labelColor: '$muted',
            valueColor: '$text',
            visibility: { kind: 'whenPresent', path: 'validFrom' },
        },
        {
            id: 'footer-bg',
            type: 'rect',
            x: 12,
            y: 520,
            w: 336,
            h: 28,
            fill: { kind: 'solid', color: '$background' },
        },
        {
            id: 'footer-text',
            type: 'text',
            x: 180,
            y: 538,
            content: { kind: 'static', value: 'Verifiable Credential' },
            font: 'heading',
            size: 11,
            weight: 700,
            color: '$secondary',
            align: 'middle',
        },
    ],
};
