import type { CredentialTemplate, Theme } from '../ir/types';

/**
 * Formal class credential template, re-authored natively in IR from a Figma reference
 * (see `examples/render-method-designer/sample-svgs/sample-class-figma.svg`). The
 * reference's text-as-path glyphs and complex masks aren't directly importable, so this
 * is hand-composed to match the layout while keeping every text + binding editable.
 *
 * Portrait orientation matching the reference (315×570), with a strong green border, a
 * compact header band, centered ceremonial copy, and a footer with issuer + date.
 */

const formalTheme: Theme = {
    colors: {
        primary: '#059669',
        secondary: '#047857',
        accent: '#10B981',
        surface: '#FFFFFF',
        text: '#064E3B',
        muted: '#6B7280',
        border: '#E5E7EB',
        background: '#F9FAFB',
    },
    fonts: {
        heading: 'Poppins, system-ui, sans-serif',
        body: 'Inter, system-ui, sans-serif',
    },
};

export const classFormalTemplate: CredentialTemplate = {
    version: 1,
    name: 'Class — Formal',
    size: { w: 315, h: 570 },
    theme: formalTheme,
    elements: [
        {
            id: 'card-bg',
            type: 'rect',
            x: 1.5,
            y: 1.5,
            w: 312,
            h: 567,
            rx: 13.5,
            fill: { kind: 'solid', color: '$surface' },
            stroke: { color: '$primary', width: 3 },
        },
        {
            id: 'header-divider',
            type: 'divider',
            x: 15,
            y: 70,
            w: 285,
            color: '$border',
            thickness: 1,
        },
        {
            id: 'header-label',
            type: 'text',
            x: 157,
            y: 50,
            content: { kind: 'static', value: 'CLASS CREDENTIAL' },
            font: 'heading',
            size: 12,
            weight: 700,
            color: '$primary',
            align: 'middle',
            letterSpacing: 2,
        },
        {
            id: 'header-issuer',
            type: 'text',
            x: 157,
            y: 62,
            content: {
                kind: 'binding',
                path: 'issuer.name',
                fallback: 'Issuing Institution',
            },
            font: 'body',
            size: 10,
            weight: 500,
            color: '$muted',
            align: 'middle',
        },
        {
            id: 'seal-bg',
            type: 'rect',
            x: 117.5,
            y: 100,
            w: 80,
            h: 80,
            rx: 40,
            fill: { kind: 'solid', color: '$background' },
            stroke: { color: '$primary', width: 2 },
        },
        {
            id: 'seal-image',
            type: 'image',
            x: 122.5,
            y: 105,
            w: 70,
            h: 70,
            source: { kind: 'binding', path: 'credentialSubject.achievement.image' },
            fit: 'cover',
            clip: 'circle',
        },
        {
            id: 'eyebrow',
            type: 'text',
            x: 157,
            y: 220,
            content: { kind: 'static', value: 'This certifies that' },
            font: 'body',
            size: 11,
            weight: 400,
            color: '$muted',
            align: 'middle',
            letterSpacing: 0.4,
        },
        {
            id: 'recipient-name',
            type: 'text',
            x: 157,
            y: 258,
            maxWidth: 280,
            content: {
                kind: 'binding',
                path: 'credentialSubject.name',
                fallback: 'Recipient Name',
            },
            font: 'heading',
            size: 22,
            weight: 700,
            color: '$text',
            align: 'middle',
        },
        {
            id: 'recipient-underline',
            type: 'divider',
            x: 65,
            y: 274,
            w: 185,
            color: '$primary',
            thickness: 1,
        },
        {
            id: 'completion-eyebrow',
            type: 'text',
            x: 157,
            y: 308,
            content: { kind: 'static', value: 'has successfully completed' },
            font: 'body',
            size: 11,
            weight: 400,
            color: '$muted',
            align: 'middle',
            letterSpacing: 0.4,
        },
        {
            id: 'achievement-name',
            type: 'text',
            x: 157,
            y: 344,
            maxWidth: 280,
            content: {
                kind: 'binding',
                path: 'credentialSubject.achievement.name',
                fallback: 'Course Name',
            },
            font: 'heading',
            size: 18,
            weight: 600,
            color: '$primary',
            align: 'middle',
        },
        {
            id: 'description',
            type: 'text',
            x: 157,
            y: 372,
            maxWidth: 280,
            content: {
                kind: 'binding',
                path: 'credentialSubject.achievement.description',
            },
            font: 'body',
            size: 11,
            weight: 400,
            color: '$muted',
            align: 'middle',
            visibility: {
                kind: 'whenPresent',
                path: 'credentialSubject.achievement.description',
            },
        },
        {
            id: 'footer-divider',
            type: 'divider',
            x: 50,
            y: 470,
            w: 215,
            color: '$border',
            thickness: 1,
        },
        {
            id: 'date-label',
            type: 'text',
            x: 65,
            y: 500,
            content: { kind: 'static', value: 'ISSUED' },
            font: 'heading',
            size: 9,
            weight: 700,
            color: '$muted',
            align: 'start',
            letterSpacing: 1.2,
        },
        {
            id: 'date-value',
            type: 'text',
            x: 65,
            y: 518,
            content: { kind: 'binding', path: 'validFrom', format: 'long', fallback: '—' },
            font: 'heading',
            size: 12,
            weight: 600,
            color: '$text',
            align: 'start',
        },
        {
            id: 'verify-label',
            type: 'text',
            x: 250,
            y: 500,
            content: { kind: 'static', value: 'VERIFIED' },
            font: 'heading',
            size: 9,
            weight: 700,
            color: '$primary',
            align: 'end',
            letterSpacing: 1.2,
        },
        {
            id: 'verify-id',
            type: 'text',
            x: 250,
            y: 518,
            content: { kind: 'binding', path: 'id', format: 'short', fallback: '—' },
            font: 'heading',
            size: 10,
            weight: 600,
            color: '$text',
            align: 'end',
        },
        {
            id: 'footer-mark',
            type: 'text',
            x: 157,
            y: 550,
            content: { kind: 'static', value: 'Verifiable Credential' },
            font: 'heading',
            size: 9,
            weight: 600,
            color: '$primary',
            align: 'middle',
            letterSpacing: 1.8,
        },
    ],
};
