import type { CredentialTemplate, Theme } from '../ir/types';

const minimalTheme: Theme = {
    colors: {
        primary: '#000000',
        secondary: '#404040',
        accent: '#000000',
        surface: '#FAFAFA',
        text: '#000000',
        muted: '#737373',
        border: '#E5E5E5',
        background: '#FAFAFA',
    },
    fonts: {
        heading: 'Inter, system-ui, sans-serif',
        body: 'Inter, system-ui, sans-serif',
    },
};

export const minimalTemplate: CredentialTemplate = {
    version: 1,
    name: 'Minimal',
    size: { w: 360, h: 560 },
    theme: minimalTheme,
    elements: [
        {
            id: 'bg',
            type: 'rect',
            x: 0,
            y: 0,
            w: 360,
            h: 560,
            rx: 16,
            fill: { kind: 'solid', color: '$surface' },
            stroke: { color: '$border', width: 1 },
        },
        {
            id: 'header-rule',
            type: 'rect',
            x: 36,
            y: 36,
            w: 32,
            h: 2,
            fill: { kind: 'solid', color: '$primary' },
        },
        {
            id: 'eyebrow',
            type: 'text',
            x: 36,
            y: 70,
            content: { kind: 'static', value: 'VERIFIABLE CREDENTIAL' },
            font: 'heading',
            size: 10,
            weight: 600,
            color: '$muted',
            align: 'start',
            letterSpacing: 1.6,
        },
        {
            id: 'title',
            type: 'text',
            x: 36,
            y: 144,
            maxWidth: 288,
            content: {
                kind: 'binding',
                path: 'credentialSubject.achievement.name',
                fallback: 'Untitled',
            },
            font: 'heading',
            size: 28,
            weight: 700,
            color: '$text',
            align: 'start',
        },
        {
            id: 'subtitle',
            type: 'text',
            x: 36,
            y: 178,
            content: {
                kind: 'binding',
                path: 'credentialSubject.achievement.achievementType',
            },
            font: 'body',
            size: 13,
            weight: 400,
            color: '$muted',
            align: 'start',
            visibility: { kind: 'whenPresent', path: 'credentialSubject.achievement.achievementType' },
        },
        {
            id: 'divider-1',
            type: 'divider',
            x: 36,
            y: 248,
            w: 288,
            color: '$border',
            thickness: 1,
        },
        {
            id: 'subject-label',
            type: 'text',
            x: 36,
            y: 282,
            content: { kind: 'static', value: 'Recipient' },
            font: 'body',
            size: 11,
            weight: 400,
            color: '$muted',
            align: 'start',
        },
        {
            id: 'subject-name',
            type: 'text',
            x: 36,
            y: 308,
            content: {
                kind: 'binding',
                path: 'credentialSubject.name',
                fallback: '—',
            },
            font: 'heading',
            size: 17,
            weight: 600,
            color: '$text',
            align: 'start',
        },
        {
            id: 'divider-2',
            type: 'divider',
            x: 36,
            y: 350,
            w: 288,
            color: '$border',
            thickness: 1,
        },
        {
            id: 'issuer-label',
            type: 'text',
            x: 36,
            y: 384,
            content: { kind: 'static', value: 'Issued by' },
            font: 'body',
            size: 11,
            weight: 400,
            color: '$muted',
            align: 'start',
        },
        {
            id: 'issuer-name',
            type: 'text',
            x: 36,
            y: 410,
            content: {
                kind: 'binding',
                path: 'issuer.name',
                fallback: '—',
            },
            font: 'heading',
            size: 17,
            weight: 600,
            color: '$text',
            align: 'start',
        },
        {
            id: 'divider-3',
            type: 'divider',
            x: 36,
            y: 452,
            w: 288,
            color: '$border',
            thickness: 1,
        },
        {
            id: 'date-label',
            type: 'text',
            x: 36,
            y: 486,
            content: { kind: 'static', value: 'Issued' },
            font: 'body',
            size: 11,
            weight: 400,
            color: '$muted',
            align: 'start',
        },
        {
            id: 'date-value',
            type: 'text',
            x: 36,
            y: 512,
            content: { kind: 'binding', path: 'validFrom', format: 'long', fallback: '—' },
            font: 'heading',
            size: 14,
            weight: 500,
            color: '$text',
            align: 'start',
        },
    ],
};
