import type { CredentialTemplate, Theme } from '../ir/types';

const modernTheme: Theme = {
    colors: {
        primary: '#0F172A',
        secondary: '#1E293B',
        accent: '#22D3EE',
        surface: '#FFFFFF',
        text: '#0F172A',
        muted: '#64748B',
        border: '#E2E8F0',
        background: '#F8FAFC',
    },
    fonts: {
        heading: 'Poppins, system-ui, sans-serif',
        body: 'Poppins, system-ui, sans-serif',
    },
};

export const modernTemplate: CredentialTemplate = {
    version: 1,
    name: 'Modern Bold',
    size: { w: 360, h: 560 },
    theme: modernTheme,
    elements: [
        {
            id: 'bg',
            type: 'rect',
            x: 0,
            y: 0,
            w: 360,
            h: 560,
            rx: 32,
            fill: {
                kind: 'linear-gradient',
                from: '$primary',
                to: '$secondary',
                direction: 'diagonal',
            },
        },
        {
            id: 'corner-accent',
            type: 'rect',
            x: 268,
            y: 28,
            w: 60,
            h: 60,
            rx: 30,
            fill: { kind: 'solid', color: '$accent' },
        },
        {
            id: 'header-eyebrow',
            type: 'text',
            x: 32,
            y: 56,
            content: { kind: 'static', value: 'CREDENTIAL' },
            font: 'heading',
            size: 11,
            weight: 600,
            color: '$accent',
            align: 'start',
            letterSpacing: 2.4,
        },
        {
            id: 'header-title',
            type: 'text',
            x: 32,
            y: 96,
            content: {
                kind: 'binding',
                path: 'credentialSubject.achievement.achievementType',
                fallback: 'Achievement',
            },
            font: 'heading',
            size: 14,
            weight: 500,
            color: '$surface',
            align: 'start',
        },
        {
            id: 'spacer-line',
            type: 'rect',
            x: 32,
            y: 152,
            w: 36,
            h: 3,
            rx: 1.5,
            fill: { kind: 'solid', color: '$accent' },
        },
        {
            id: 'title',
            type: 'text',
            x: 32,
            y: 218,
            maxWidth: 296,
            content: {
                kind: 'binding',
                path: 'credentialSubject.achievement.name',
                fallback: 'Untitled Achievement',
            },
            font: 'heading',
            size: 32,
            weight: 700,
            color: '$surface',
            align: 'start',
        },
        {
            id: 'description',
            type: 'text',
            x: 32,
            y: 262,
            content: {
                kind: 'binding',
                path: 'credentialSubject.achievement.description',
            },
            font: 'body',
            size: 13,
            weight: 400,
            color: '#CBD5E1',
            align: 'start',
            visibility: { kind: 'whenPresent', path: 'credentialSubject.achievement.description' },
        },
        {
            id: 'card-panel',
            type: 'rect',
            x: 24,
            y: 320,
            w: 312,
            h: 196,
            rx: 20,
            fill: { kind: 'solid', color: '#FFFFFF14' },
        },
        {
            id: 'subject-label',
            type: 'text',
            x: 48,
            y: 354,
            content: { kind: 'static', value: 'RECIPIENT' },
            font: 'heading',
            size: 10,
            weight: 700,
            color: '$accent',
            align: 'start',
            letterSpacing: 1.4,
        },
        {
            id: 'subject-name',
            type: 'text',
            x: 48,
            y: 380,
            content: {
                kind: 'binding',
                path: 'credentialSubject.name',
                fallback: 'Recipient',
            },
            font: 'heading',
            size: 20,
            weight: 600,
            color: '$surface',
            align: 'start',
        },
        {
            id: 'issuer-label',
            type: 'text',
            x: 48,
            y: 432,
            content: { kind: 'static', value: 'ISSUED BY' },
            font: 'heading',
            size: 10,
            weight: 700,
            color: '$accent',
            align: 'start',
            letterSpacing: 1.4,
        },
        {
            id: 'issuer-name',
            type: 'text',
            x: 48,
            y: 456,
            content: {
                kind: 'binding',
                path: 'issuer.name',
                fallback: 'Issuer',
            },
            font: 'heading',
            size: 14,
            weight: 500,
            color: '$surface',
            align: 'start',
        },
        {
            id: 'date-label',
            type: 'text',
            x: 48,
            y: 488,
            content: { kind: 'static', value: 'ISSUED' },
            font: 'heading',
            size: 10,
            weight: 700,
            color: '$accent',
            align: 'start',
            letterSpacing: 1.4,
        },
        {
            id: 'date-value',
            type: 'text',
            x: 320,
            y: 488,
            content: { kind: 'binding', path: 'validFrom', format: 'medium', fallback: '—' },
            font: 'heading',
            size: 12,
            weight: 500,
            color: '$surface',
            align: 'end',
        },
    ],
};
