# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_store_send_app_notification_request import AppStoreSendAppNotificationRequest

class TestAppStoreSendAppNotificationRequest(unittest.TestCase):
    """AppStoreSendAppNotificationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppStoreSendAppNotificationRequest:
        """Test AppStoreSendAppNotificationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppStoreSendAppNotificationRequest`
        """
        model = AppStoreSendAppNotificationRequest()
        if include_optional:
            return AppStoreSendAppNotificationRequest(
                recipient = '',
                title = '',
                body = '',
                action_path = '',
                category = '',
                priority = 'normal'
            )
        else:
            return AppStoreSendAppNotificationRequest(
                recipient = '',
        )
        """

    def testAppStoreSendAppNotificationRequest(self):
        """Test AppStoreSendAppNotificationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
