# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.profile_list_invites200_response_inner import ProfileListInvites200ResponseInner

class TestProfileListInvites200ResponseInner(unittest.TestCase):
    """ProfileListInvites200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileListInvites200ResponseInner:
        """Test ProfileListInvites200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileListInvites200ResponseInner`
        """
        model = ProfileListInvites200ResponseInner()
        if include_optional:
            return ProfileListInvites200ResponseInner(
                challenge = '',
                expires_in = 1.337,
                uses_remaining = 1.337,
                max_uses = 1.337
            )
        else:
            return ProfileListInvites200ResponseInner(
                challenge = '',
                expires_in = 1.337,
                uses_remaining = 1.337,
                max_uses = 1.337,
        )
        """

    def testProfileListInvites200ResponseInner(self):
        """Test ProfileListInvites200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
