# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.inbox_issue_batch202_response import InboxIssueBatch202Response

class TestInboxIssueBatch202Response(unittest.TestCase):
    """InboxIssueBatch202Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InboxIssueBatch202Response:
        """Test InboxIssueBatch202Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InboxIssueBatch202Response`
        """
        model = InboxIssueBatch202Response()
        if include_optional:
            return InboxIssueBatch202Response(
                batch_id = '',
                status = 'QUEUED',
                created_at = ''
            )
        else:
            return InboxIssueBatch202Response(
                batch_id = '',
                status = 'QUEUED',
                created_at = '',
        )
        """

    def testInboxIssueBatch202Response(self):
        """Test InboxIssueBatch202Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
