# coding: utf-8

"""
    LearnCard Network Profile Service API

    This is the API for interacting with a LearnCard Network Profile Service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.boost_send_boost_request_credential_any_of_proof_any_of import BoostSendBoostRequestCredentialAnyOfProofAnyOf

class TestBoostSendBoostRequestCredentialAnyOfProofAnyOf(unittest.TestCase):
    """BoostSendBoostRequestCredentialAnyOfProofAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BoostSendBoostRequestCredentialAnyOfProofAnyOf:
        """Test BoostSendBoostRequestCredentialAnyOfProofAnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BoostSendBoostRequestCredentialAnyOfProofAnyOf`
        """
        model = BoostSendBoostRequestCredentialAnyOfProofAnyOf()
        if include_optional:
            return BoostSendBoostRequestCredentialAnyOfProofAnyOf(
                type = '',
                created = '',
                challenge = '',
                domain = '',
                nonce = '',
                proof_purpose = '',
                verification_method = '',
                jws = ''
            )
        else:
            return BoostSendBoostRequestCredentialAnyOfProofAnyOf(
                type = '',
                created = '',
                proof_purpose = '',
                verification_method = '',
        )
        """

    def testBoostSendBoostRequestCredentialAnyOfProofAnyOf(self):
        """Test BoostSendBoostRequestCredentialAnyOfProofAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
