# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.boost_get_boosts_request_query_any_of_or_inner_status import BoostGetBoostsRequestQueryAnyOfOrInnerStatus

class TestBoostGetBoostsRequestQueryAnyOfOrInnerStatus(unittest.TestCase):
    """BoostGetBoostsRequestQueryAnyOfOrInnerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BoostGetBoostsRequestQueryAnyOfOrInnerStatus:
        """Test BoostGetBoostsRequestQueryAnyOfOrInnerStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BoostGetBoostsRequestQueryAnyOfOrInnerStatus`
        """
        model = BoostGetBoostsRequestQueryAnyOfOrInnerStatus()
        if include_optional:
            return BoostGetBoostsRequestQueryAnyOfOrInnerStatus(
                var_in = [
                    'DRAFT'
                    ]
            )
        else:
            return BoostGetBoostsRequestQueryAnyOfOrInnerStatus(
                var_in = [
                    'DRAFT'
                    ],
        )
        """

    def testBoostGetBoostsRequestQueryAnyOfOrInnerStatus(self):
        """Test BoostGetBoostsRequestQueryAnyOfOrInnerStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
