# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.integrations_get_integrations_request import IntegrationsGetIntegrationsRequest

class TestIntegrationsGetIntegrationsRequest(unittest.TestCase):
    """IntegrationsGetIntegrationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegrationsGetIntegrationsRequest:
        """Test IntegrationsGetIntegrationsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegrationsGetIntegrationsRequest`
        """
        model = IntegrationsGetIntegrationsRequest()
        if include_optional:
            return IntegrationsGetIntegrationsRequest(
                limit = 1.337,
                cursor = '',
                query = openapi_client.models.integrations_get_integrations_request_query.integrations_getIntegrations_request_query(
                    id = null, 
                    name = null, 
                    description = null, 
                    status = null, 
                    guide_type = null, )
            )
        else:
            return IntegrationsGetIntegrationsRequest(
        )
        """

    def testIntegrationsGetIntegrationsRequest(self):
        """Test IntegrationsGetIntegrationsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
