# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.contact_methods_create_contact_method_session200_response import ContactMethodsCreateContactMethodSession200Response

class TestContactMethodsCreateContactMethodSession200Response(unittest.TestCase):
    """ContactMethodsCreateContactMethodSession200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactMethodsCreateContactMethodSession200Response:
        """Test ContactMethodsCreateContactMethodSession200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactMethodsCreateContactMethodSession200Response`
        """
        model = ContactMethodsCreateContactMethodSession200Response()
        if include_optional:
            return ContactMethodsCreateContactMethodSession200Response(
                session_jwt = ''
            )
        else:
            return ContactMethodsCreateContactMethodSession200Response(
                session_jwt = '',
        )
        """

    def testContactMethodsCreateContactMethodSession200Response(self):
        """Test ContactMethodsCreateContactMethodSession200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
