# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.claim_hook_get_claim_hooks_for_boost200_response_records_inner_all_of_one_of1_data import ClaimHookGetClaimHooksForBoost200ResponseRecordsInnerAllOfOneOf1Data

class TestClaimHookGetClaimHooksForBoost200ResponseRecordsInnerAllOfOneOf1Data(unittest.TestCase):
    """ClaimHookGetClaimHooksForBoost200ResponseRecordsInnerAllOfOneOf1Data unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClaimHookGetClaimHooksForBoost200ResponseRecordsInnerAllOfOneOf1Data:
        """Test ClaimHookGetClaimHooksForBoost200ResponseRecordsInnerAllOfOneOf1Data
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClaimHookGetClaimHooksForBoost200ResponseRecordsInnerAllOfOneOf1Data`
        """
        model = ClaimHookGetClaimHooksForBoost200ResponseRecordsInnerAllOfOneOf1Data()
        if include_optional:
            return ClaimHookGetClaimHooksForBoost200ResponseRecordsInnerAllOfOneOf1Data(
                claim_uri = '',
                target_uri = ''
            )
        else:
            return ClaimHookGetClaimHooksForBoost200ResponseRecordsInnerAllOfOneOf1Data(
                claim_uri = '',
                target_uri = '',
        )
        """

    def testClaimHookGetClaimHooksForBoost200ResponseRecordsInnerAllOfOneOf1Data(self):
        """Test ClaimHookGetClaimHooksForBoost200ResponseRecordsInnerAllOfOneOf1Data"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
