# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.profile_set_primary_signing_authority_request import ProfileSetPrimarySigningAuthorityRequest

class TestProfileSetPrimarySigningAuthorityRequest(unittest.TestCase):
    """ProfileSetPrimarySigningAuthorityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileSetPrimarySigningAuthorityRequest:
        """Test ProfileSetPrimarySigningAuthorityRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileSetPrimarySigningAuthorityRequest`
        """
        model = ProfileSetPrimarySigningAuthorityRequest()
        if include_optional:
            return ProfileSetPrimarySigningAuthorityRequest(
                endpoint = '',
                name = 'p'
            )
        else:
            return ProfileSetPrimarySigningAuthorityRequest(
                endpoint = '',
                name = 'p',
        )
        """

    def testProfileSetPrimarySigningAuthorityRequest(self):
        """Test ProfileSetPrimarySigningAuthorityRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
