# coding: utf-8

"""
    LearnCard Network Profile Service API

    This is the API for interacting with a LearnCard Network Profile Service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.boost_send_boost_request_credential_any_of1_recipients_inner_header import BoostSendBoostRequestCredentialAnyOf1RecipientsInnerHeader

class TestBoostSendBoostRequestCredentialAnyOf1RecipientsInnerHeader(unittest.TestCase):
    """BoostSendBoostRequestCredentialAnyOf1RecipientsInnerHeader unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BoostSendBoostRequestCredentialAnyOf1RecipientsInnerHeader:
        """Test BoostSendBoostRequestCredentialAnyOf1RecipientsInnerHeader
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BoostSendBoostRequestCredentialAnyOf1RecipientsInnerHeader`
        """
        model = BoostSendBoostRequestCredentialAnyOf1RecipientsInnerHeader()
        if include_optional:
            return BoostSendBoostRequestCredentialAnyOf1RecipientsInnerHeader(
                alg = '',
                iv = '',
                tag = '',
                epk = openapi_client.models.boost_send_boost_request_credential_any_of_1_recipients_inner_header_epk.boost_sendBoost_request_credential_anyOf_1_recipients_inner_header_epk(
                    kty = '', 
                    crv = '', 
                    x = '', 
                    y = '', 
                    n = '', 
                    d = '', ),
                kid = '',
                apv = '',
                apu = ''
            )
        else:
            return BoostSendBoostRequestCredentialAnyOf1RecipientsInnerHeader(
                alg = '',
                iv = '',
                tag = '',
        )
        """

    def testBoostSendBoostRequestCredentialAnyOf1RecipientsInnerHeader(self):
        """Test BoostSendBoostRequestCredentialAnyOf1RecipientsInnerHeader"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
