# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.contracts_get_consented_contracts200_response_records_inner_terms_read_credentials import ContractsGetConsentedContracts200ResponseRecordsInnerTermsReadCredentials

class TestContractsGetConsentedContracts200ResponseRecordsInnerTermsReadCredentials(unittest.TestCase):
    """ContractsGetConsentedContracts200ResponseRecordsInnerTermsReadCredentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContractsGetConsentedContracts200ResponseRecordsInnerTermsReadCredentials:
        """Test ContractsGetConsentedContracts200ResponseRecordsInnerTermsReadCredentials
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContractsGetConsentedContracts200ResponseRecordsInnerTermsReadCredentials`
        """
        model = ContractsGetConsentedContracts200ResponseRecordsInnerTermsReadCredentials()
        if include_optional:
            return ContractsGetConsentedContracts200ResponseRecordsInnerTermsReadCredentials(
                share_all = True,
                sharing = True,
                categories = {
                    'key' : openapi_client.models.contracts_get_consented_contracts_200_response_records_inner_terms_read_credentials_categories_value.contracts_getConsentedContracts_200_response_records_inner_terms_read_credentials_categories_value(
                        sharing = True, 
                        shared = [
                            ''
                            ], 
                        share_all = True, 
                        share_until = '', )
                    }
            )
        else:
            return ContractsGetConsentedContracts200ResponseRecordsInnerTermsReadCredentials(
                categories = {
                    'key' : openapi_client.models.contracts_get_consented_contracts_200_response_records_inner_terms_read_credentials_categories_value.contracts_getConsentedContracts_200_response_records_inner_terms_read_credentials_categories_value(
                        sharing = True, 
                        shared = [
                            ''
                            ], 
                        share_all = True, 
                        share_until = '', )
                    },
        )
        """

    def testContractsGetConsentedContracts200ResponseRecordsInnerTermsReadCredentials(self):
        """Test ContractsGetConsentedContracts200ResponseRecordsInnerTermsReadCredentials"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
