# coding: utf-8

"""
    LearnCard Network Profile Service API

    This is the API for interacting with a LearnCard Network Profile Service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.did_metadata_add_did_metadata_request_service_inner import DidMetadataAddDidMetadataRequestServiceInner

class TestDidMetadataAddDidMetadataRequestServiceInner(unittest.TestCase):
    """DidMetadataAddDidMetadataRequestServiceInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DidMetadataAddDidMetadataRequestServiceInner:
        """Test DidMetadataAddDidMetadataRequestServiceInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DidMetadataAddDidMetadataRequestServiceInner`
        """
        model = DidMetadataAddDidMetadataRequestServiceInner()
        if include_optional:
            return DidMetadataAddDidMetadataRequestServiceInner(
                id = '',
                type = None,
                service_endpoint = None
            )
        else:
            return DidMetadataAddDidMetadataRequestServiceInner(
                id = '',
                type = None,
        )
        """

    def testDidMetadataAddDidMetadataRequestServiceInner(self):
        """Test DidMetadataAddDidMetadataRequestServiceInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
