# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.skill_frameworks_get_boosts_that_use_framework_request import SkillFrameworksGetBoostsThatUseFrameworkRequest

class TestSkillFrameworksGetBoostsThatUseFrameworkRequest(unittest.TestCase):
    """SkillFrameworksGetBoostsThatUseFrameworkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SkillFrameworksGetBoostsThatUseFrameworkRequest:
        """Test SkillFrameworksGetBoostsThatUseFrameworkRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SkillFrameworksGetBoostsThatUseFrameworkRequest`
        """
        model = SkillFrameworksGetBoostsThatUseFrameworkRequest()
        if include_optional:
            return SkillFrameworksGetBoostsThatUseFrameworkRequest(
                limit = 1,
                cursor = '',
                query = None
            )
        else:
            return SkillFrameworksGetBoostsThatUseFrameworkRequest(
        )
        """

    def testSkillFrameworksGetBoostsThatUseFrameworkRequest(self):
        """Test SkillFrameworksGetBoostsThatUseFrameworkRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
