# coding: utf-8

"""
    LearnCard Network Profile Service API

    This is the API for interacting with a LearnCard Network Profile Service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.profile_signing_authority200_response import ProfileSigningAuthority200Response

class TestProfileSigningAuthority200Response(unittest.TestCase):
    """ProfileSigningAuthority200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileSigningAuthority200Response:
        """Test ProfileSigningAuthority200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileSigningAuthority200Response`
        """
        model = ProfileSigningAuthority200Response()
        if include_optional:
            return ProfileSigningAuthority200Response(
                signing_authority = openapi_client.models.profile_signing_authorities_200_response_inner_signing_authority.profile_signingAuthorities_200_response_inner_signingAuthority(
                    endpoint = '', ),
                relationship = openapi_client.models.profile_signing_authorities_200_response_inner_relationship.profile_signingAuthorities_200_response_inner_relationship(
                    name = 'p', 
                    did = '', )
            )
        else:
            return ProfileSigningAuthority200Response(
                signing_authority = openapi_client.models.profile_signing_authorities_200_response_inner_signing_authority.profile_signingAuthorities_200_response_inner_signingAuthority(
                    endpoint = '', ),
                relationship = openapi_client.models.profile_signing_authorities_200_response_inner_relationship.profile_signingAuthorities_200_response_inner_relationship(
                    name = 'p', 
                    did = '', ),
        )
        """

    def testProfileSigningAuthority200Response(self):
        """Test ProfileSigningAuthority200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
