# coding: utf-8

"""
    LearnCard Network Profile Service API

    This is the API for interacting with a LearnCard Network Profile Service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.did_metadata_get_did_metadata200_response import DidMetadataGetDidMetadata200Response

class TestDidMetadataGetDidMetadata200Response(unittest.TestCase):
    """DidMetadataGetDidMetadata200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DidMetadataGetDidMetadata200Response:
        """Test DidMetadataGetDidMetadata200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DidMetadataGetDidMetadata200Response`
        """
        model = DidMetadataGetDidMetadata200Response()
        if include_optional:
            return DidMetadataGetDidMetadata200Response(
                context = [
                    null
                    ],
                id = '',
                also_known_as = '',
                controller = None,
                verification_method = [
                    null
                    ],
                authentication = [
                    null
                    ],
                assertion_method = [
                    null
                    ],
                key_agreement = [
                    null
                    ],
                capability_invocation = [
                    null
                    ],
                capability_delegation = [
                    null
                    ],
                public_key = [
                    null
                    ],
                service = [
                    {
                        'key' : null
                        }
                    ],
                proof = None
            )
        else:
            return DidMetadataGetDidMetadata200Response(
        )
        """

    def testDidMetadataGetDidMetadata200Response(self):
        """Test DidMetadataGetDidMetadata200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
