# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.contracts_cancel_contract_request_request import ContractsCancelContractRequestRequest

class TestContractsCancelContractRequestRequest(unittest.TestCase):
    """ContractsCancelContractRequestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContractsCancelContractRequestRequest:
        """Test ContractsCancelContractRequestRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContractsCancelContractRequestRequest`
        """
        model = ContractsCancelContractRequestRequest()
        if include_optional:
            return ContractsCancelContractRequestRequest(
                contract_uri = '',
                target_profile_id = ''
            )
        else:
            return ContractsCancelContractRequestRequest(
                contract_uri = '',
                target_profile_id = '',
        )
        """

    def testContractsCancelContractRequestRequest(self):
        """Test ContractsCancelContractRequestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
