# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.contact_methods_verify_contact_method_request import ContactMethodsVerifyContactMethodRequest

class TestContactMethodsVerifyContactMethodRequest(unittest.TestCase):
    """ContactMethodsVerifyContactMethodRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactMethodsVerifyContactMethodRequest:
        """Test ContactMethodsVerifyContactMethodRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactMethodsVerifyContactMethodRequest`
        """
        model = ContactMethodsVerifyContactMethodRequest()
        if include_optional:
            return ContactMethodsVerifyContactMethodRequest(
                token = ''
            )
        else:
            return ContactMethodsVerifyContactMethodRequest(
                token = '',
        )
        """

    def testContactMethodsVerifyContactMethodRequest(self):
        """Test ContactMethodsVerifyContactMethodRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
