# coding: utf-8

"""
    LearnCard Network Profile Service API

    This is the API for interacting with a LearnCard Network Profile Service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.claim_hook_get_claim_hooks_for_boost_request import ClaimHookGetClaimHooksForBoostRequest

class TestClaimHookGetClaimHooksForBoostRequest(unittest.TestCase):
    """ClaimHookGetClaimHooksForBoostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClaimHookGetClaimHooksForBoostRequest:
        """Test ClaimHookGetClaimHooksForBoostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClaimHookGetClaimHooksForBoostRequest`
        """
        model = ClaimHookGetClaimHooksForBoostRequest()
        if include_optional:
            return ClaimHookGetClaimHooksForBoostRequest(
                limit = 1.337,
                cursor = '',
                sort = '',
                query = openapi_client.models.claim_hook_get_claim_hooks_for_boost_request_query.claimHook_getClaimHooksForBoost_request_query(
                    type = null, 
                    data = openapi_client.models.claim_hook_get_claim_hooks_for_boost_request_query_data.claimHook_getClaimHooksForBoost_request_query_data(
                        claim_uri = null, 
                        target_uri = null, 
                        permissions = openapi_client.models.claim_hook_get_claim_hooks_for_boost_request_query_data_permissions.claimHook_getClaimHooksForBoost_request_query_data_permissions(
                            role = null, 
                            can_edit = True, 
                            can_issue = True, 
                            can_revoke = True, 
                            can_manage_permissions = True, 
                            can_issue_children = null, 
                            can_create_children = null, 
                            can_edit_children = null, 
                            can_revoke_children = null, 
                            can_manage_children_permissions = null, 
                            can_manage_children_profiles = True, 
                            can_view_analytics = True, ), ), ),
                uri = ''
            )
        else:
            return ClaimHookGetClaimHooksForBoostRequest(
                uri = '',
        )
        """

    def testClaimHookGetClaimHooksForBoostRequest(self):
        """Test ClaimHookGetClaimHooksForBoostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
