# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.boost_send_boost_via_signing_authority_request import BoostSendBoostViaSigningAuthorityRequest

class TestBoostSendBoostViaSigningAuthorityRequest(unittest.TestCase):
    """BoostSendBoostViaSigningAuthorityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BoostSendBoostViaSigningAuthorityRequest:
        """Test BoostSendBoostViaSigningAuthorityRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BoostSendBoostViaSigningAuthorityRequest`
        """
        model = BoostSendBoostViaSigningAuthorityRequest()
        if include_optional:
            return BoostSendBoostViaSigningAuthorityRequest(
                boost_uri = '',
                signing_authority = openapi_client.models.boost_send_boost_via_signing_authority_request_signing_authority.boost_sendBoostViaSigningAuthority_request_signingAuthority(
                    name = '', 
                    endpoint = '', ),
                options = openapi_client.models.boost_send_boost_request_options.boost_sendBoost_request_options(
                    skip_notification = True, )
            )
        else:
            return BoostSendBoostViaSigningAuthorityRequest(
                boost_uri = '',
                signing_authority = openapi_client.models.boost_send_boost_via_signing_authority_request_signing_authority.boost_sendBoostViaSigningAuthority_request_signingAuthority(
                    name = '', 
                    endpoint = '', ),
        )
        """

    def testBoostSendBoostViaSigningAuthorityRequest(self):
        """Test BoostSendBoostViaSigningAuthorityRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
