# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.share_links_create_request import ShareLinksCreateRequest

class TestShareLinksCreateRequest(unittest.TestCase):
    """ShareLinksCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShareLinksCreateRequest:
        """Test ShareLinksCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShareLinksCreateRequest`
        """
        model = ShareLinksCreateRequest()
        if include_optional:
            return ShareLinksCreateRequest(
                id = '',
                client_request_id = 'ffffffff-ffff-ffff-ffff-ffffffffffff',
                title = '0',
                note = '',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                passcode = '01234567',
                notify_on_view = True,
                selected_count = 1,
                content_version = 1,
                envelope = openapi_client.models.share_links_create_request_envelope.shareLinks_create_request_envelope(
                    v = 1, 
                    alg = 'A256GCM', 
                    iv = '', 
                    ct = '', ),
                owner_encrypted_recovery = openapi_client.models.credential_send_credential_request_credential_any_of_1.credential_sendCredential_request_credential_anyOf_1(
                    protected = '', 
                    iv = '', 
                    ciphertext = '', 
                    tag = '', 
                    aad = '', 
                    recipients = [
                        openapi_client.models.credential_send_credential_request_credential_any_of_1_recipients_inner.credential_sendCredential_request_credential_anyOf_1_recipients_inner(
                            header = openapi_client.models.credential_send_credential_request_credential_any_of_1_recipients_inner_header.credential_sendCredential_request_credential_anyOf_1_recipients_inner_header(
                                alg = '', 
                                iv = '', 
                                tag = '', 
                                epk = openapi_client.models.credential_send_credential_request_credential_any_of_1_recipients_inner_header_epk.credential_sendCredential_request_credential_anyOf_1_recipients_inner_header_epk(
                                    kty = '', 
                                    crv = '', 
                                    x = '', 
                                    y = '', 
                                    n = '', 
                                    d = '', ), 
                                kid = '', 
                                apv = '', 
                                apu = '', ), 
                            encrypted_key = '', )
                        ], )
            )
        else:
            return ShareLinksCreateRequest(
                id = '',
                client_request_id = 'ffffffff-ffff-ffff-ffff-ffffffffffff',
                title = '0',
                selected_count = 1,
                content_version = 1,
                envelope = openapi_client.models.share_links_create_request_envelope.shareLinks_create_request_envelope(
                    v = 1, 
                    alg = 'A256GCM', 
                    iv = '', 
                    ct = '', ),
                owner_encrypted_recovery = openapi_client.models.credential_send_credential_request_credential_any_of_1.credential_sendCredential_request_credential_anyOf_1(
                    protected = '', 
                    iv = '', 
                    ciphertext = '', 
                    tag = '', 
                    aad = '', 
                    recipients = [
                        openapi_client.models.credential_send_credential_request_credential_any_of_1_recipients_inner.credential_sendCredential_request_credential_anyOf_1_recipients_inner(
                            header = openapi_client.models.credential_send_credential_request_credential_any_of_1_recipients_inner_header.credential_sendCredential_request_credential_anyOf_1_recipients_inner_header(
                                alg = '', 
                                iv = '', 
                                tag = '', 
                                epk = openapi_client.models.credential_send_credential_request_credential_any_of_1_recipients_inner_header_epk.credential_sendCredential_request_credential_anyOf_1_recipients_inner_header_epk(
                                    kty = '', 
                                    crv = '', 
                                    x = '', 
                                    y = '', 
                                    n = '', 
                                    d = '', ), 
                                kid = '', 
                                apv = '', 
                                apu = '', ), 
                            encrypted_key = '', )
                        ], ),
        )
        """

    def testShareLinksCreateRequest(self):
        """Test ShareLinksCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
