# coding: utf-8

"""
    LearnCard Network Profile Service API

    This is the API for interacting with a LearnCard Network Profile Service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.boost_send_boost_request_credential_any_of_issuer_any_of_address import BoostSendBoostRequestCredentialAnyOfIssuerAnyOfAddress

class TestBoostSendBoostRequestCredentialAnyOfIssuerAnyOfAddress(unittest.TestCase):
    """BoostSendBoostRequestCredentialAnyOfIssuerAnyOfAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BoostSendBoostRequestCredentialAnyOfIssuerAnyOfAddress:
        """Test BoostSendBoostRequestCredentialAnyOfIssuerAnyOfAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BoostSendBoostRequestCredentialAnyOfIssuerAnyOfAddress`
        """
        model = BoostSendBoostRequestCredentialAnyOfIssuerAnyOfAddress()
        if include_optional:
            return BoostSendBoostRequestCredentialAnyOfIssuerAnyOfAddress(
                type = None,
                address_country = '',
                address_country_code = '',
                address_region = '',
                address_locality = '',
                street_address = '',
                post_office_box_number = '',
                postal_code = '',
                geo = openapi_client.models.boost_send_boost_request_credential_any_of_issuer_any_of_address_geo.boost_sendBoost_request_credential_anyOf_issuer_anyOf_address_geo(
                    type = null, 
                    latitude = 1.337, 
                    longitude = 1.337, )
            )
        else:
            return BoostSendBoostRequestCredentialAnyOfIssuerAnyOfAddress(
                type = None,
        )
        """

    def testBoostSendBoostRequestCredentialAnyOfIssuerAnyOfAddress(self):
        """Test BoostSendBoostRequestCredentialAnyOfIssuerAnyOfAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
