# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.skill_frameworks_count_boosts_that_use_framework200_response import SkillFrameworksCountBoostsThatUseFramework200Response

class TestSkillFrameworksCountBoostsThatUseFramework200Response(unittest.TestCase):
    """SkillFrameworksCountBoostsThatUseFramework200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SkillFrameworksCountBoostsThatUseFramework200Response:
        """Test SkillFrameworksCountBoostsThatUseFramework200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SkillFrameworksCountBoostsThatUseFramework200Response`
        """
        model = SkillFrameworksCountBoostsThatUseFramework200Response()
        if include_optional:
            return SkillFrameworksCountBoostsThatUseFramework200Response(
                count = 1.337
            )
        else:
            return SkillFrameworksCountBoostsThatUseFramework200Response(
                count = 1.337,
        )
        """

    def testSkillFrameworksCountBoostsThatUseFramework200Response(self):
        """Test SkillFrameworksCountBoostsThatUseFramework200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
