# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_store_add_boost_to_listing_request import AppStoreAddBoostToListingRequest

class TestAppStoreAddBoostToListingRequest(unittest.TestCase):
    """AppStoreAddBoostToListingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppStoreAddBoostToListingRequest:
        """Test AppStoreAddBoostToListingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppStoreAddBoostToListingRequest`
        """
        model = AppStoreAddBoostToListingRequest()
        if include_optional:
            return AppStoreAddBoostToListingRequest(
                boost_uri = '',
                template_alias = 'p0'
            )
        else:
            return AppStoreAddBoostToListingRequest(
                boost_uri = '',
                template_alias = 'p0',
        )
        """

    def testAppStoreAddBoostToListingRequest(self):
        """Test AppStoreAddBoostToListingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
