# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.inbox_get_my_inbox_deliveries200_response_records_inner_credential_recipients_inner_header import InboxGetMyInboxDeliveries200ResponseRecordsInnerCredentialRecipientsInnerHeader

class TestInboxGetMyInboxDeliveries200ResponseRecordsInnerCredentialRecipientsInnerHeader(unittest.TestCase):
    """InboxGetMyInboxDeliveries200ResponseRecordsInnerCredentialRecipientsInnerHeader unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InboxGetMyInboxDeliveries200ResponseRecordsInnerCredentialRecipientsInnerHeader:
        """Test InboxGetMyInboxDeliveries200ResponseRecordsInnerCredentialRecipientsInnerHeader
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InboxGetMyInboxDeliveries200ResponseRecordsInnerCredentialRecipientsInnerHeader`
        """
        model = InboxGetMyInboxDeliveries200ResponseRecordsInnerCredentialRecipientsInnerHeader()
        if include_optional:
            return InboxGetMyInboxDeliveries200ResponseRecordsInnerCredentialRecipientsInnerHeader(
                alg = '',
                iv = '',
                tag = '',
                epk = openapi_client.models.inbox_get_my_inbox_deliveries_200_response_records_inner_credential_recipients_inner_header_epk.inbox_getMyInboxDeliveries_200_response_records_inner_credential_recipients_inner_header_epk(
                    kty = '', 
                    crv = '', 
                    x = '', 
                    y = '', 
                    n = '', 
                    d = '', ),
                kid = '',
                apv = '',
                apu = ''
            )
        else:
            return InboxGetMyInboxDeliveries200ResponseRecordsInnerCredentialRecipientsInnerHeader(
                alg = '',
                iv = '',
                tag = '',
        )
        """

    def testInboxGetMyInboxDeliveries200ResponseRecordsInnerCredentialRecipientsInnerHeader(self):
        """Test InboxGetMyInboxDeliveries200ResponseRecordsInnerCredentialRecipientsInnerHeader"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
