# coding: utf-8

"""
    LearnCard Network Profile Service API

    This is the API for interacting with a LearnCard Network Profile Service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.profile_manager_get_profile_manager200_response import ProfileManagerGetProfileManager200Response

class TestProfileManagerGetProfileManager200Response(unittest.TestCase):
    """ProfileManagerGetProfileManager200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileManagerGetProfileManager200Response:
        """Test ProfileManagerGetProfileManager200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileManagerGetProfileManager200Response`
        """
        model = ProfileManagerGetProfileManager200Response()
        if include_optional:
            return ProfileManagerGetProfileManager200Response(
                id = '',
                created = '',
                display_name = '',
                short_bio = '',
                bio = '',
                email = '',
                image = '',
                hero_image = '',
                did = ''
            )
        else:
            return ProfileManagerGetProfileManager200Response(
                id = '',
                created = '',
                did = '',
        )
        """

    def testProfileManagerGetProfileManager200Response(self):
        """Test ProfileManagerGetProfileManager200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
