# coding: utf-8

"""
    LearnCard Network Profile Service API

    This is the API for interacting with a LearnCard Network Profile Service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.boost_send_boost_request_credential_any_of_refresh_service_any_of import BoostSendBoostRequestCredentialAnyOfRefreshServiceAnyOf

class TestBoostSendBoostRequestCredentialAnyOfRefreshServiceAnyOf(unittest.TestCase):
    """BoostSendBoostRequestCredentialAnyOfRefreshServiceAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BoostSendBoostRequestCredentialAnyOfRefreshServiceAnyOf:
        """Test BoostSendBoostRequestCredentialAnyOfRefreshServiceAnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BoostSendBoostRequestCredentialAnyOfRefreshServiceAnyOf`
        """
        model = BoostSendBoostRequestCredentialAnyOfRefreshServiceAnyOf()
        if include_optional:
            return BoostSendBoostRequestCredentialAnyOfRefreshServiceAnyOf(
                id = '',
                type = ''
            )
        else:
            return BoostSendBoostRequestCredentialAnyOfRefreshServiceAnyOf(
                type = '',
        )
        """

    def testBoostSendBoostRequestCredentialAnyOfRefreshServiceAnyOf(self):
        """Test BoostSendBoostRequestCredentialAnyOfRefreshServiceAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
