# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.boost_search_skills_available_for_boost200_response import BoostSearchSkillsAvailableForBoost200Response

class TestBoostSearchSkillsAvailableForBoost200Response(unittest.TestCase):
    """BoostSearchSkillsAvailableForBoost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BoostSearchSkillsAvailableForBoost200Response:
        """Test BoostSearchSkillsAvailableForBoost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BoostSearchSkillsAvailableForBoost200Response`
        """
        model = BoostSearchSkillsAvailableForBoost200Response()
        if include_optional:
            return BoostSearchSkillsAvailableForBoost200Response(
                records = [
                    openapi_client.models.boost_search_skills_available_for_boost_200_response_records_inner.boost_searchSkillsAvailableForBoost_200_response_records_inner(
                        id = '', 
                        statement = '', 
                        description = '', 
                        code = '', 
                        icon = '', 
                        type = 'skill', 
                        status = 'active', 
                        framework_id = '', )
                    ],
                has_more = True,
                cursor = ''
            )
        else:
            return BoostSearchSkillsAvailableForBoost200Response(
                records = [
                    openapi_client.models.boost_search_skills_available_for_boost_200_response_records_inner.boost_searchSkillsAvailableForBoost_200_response_records_inner(
                        id = '', 
                        statement = '', 
                        description = '', 
                        code = '', 
                        icon = '', 
                        type = 'skill', 
                        status = 'active', 
                        framework_id = '', )
                    ],
                has_more = True,
                cursor = '',
        )
        """

    def testBoostSearchSkillsAvailableForBoost200Response(self):
        """Test BoostSearchSkillsAvailableForBoost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
