# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.storage_resolve200_response_any_of_any_of1_write_credentials import StorageResolve200ResponseAnyOfAnyOf1WriteCredentials

class TestStorageResolve200ResponseAnyOfAnyOf1WriteCredentials(unittest.TestCase):
    """StorageResolve200ResponseAnyOfAnyOf1WriteCredentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StorageResolve200ResponseAnyOfAnyOf1WriteCredentials:
        """Test StorageResolve200ResponseAnyOfAnyOf1WriteCredentials
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StorageResolve200ResponseAnyOfAnyOf1WriteCredentials`
        """
        model = StorageResolve200ResponseAnyOfAnyOf1WriteCredentials()
        if include_optional:
            return StorageResolve200ResponseAnyOfAnyOf1WriteCredentials(
                categories = {
                    'key' : openapi_client.models.storage_resolve_200_response_any_of_any_of_1_read_personal_value.storage_resolve_200_response_anyOf_anyOf_1_read_personal_value(
                        required = True, 
                        default_enabled = True, )
                    }
            )
        else:
            return StorageResolve200ResponseAnyOfAnyOf1WriteCredentials(
                categories = {
                    'key' : openapi_client.models.storage_resolve_200_response_any_of_any_of_1_read_personal_value.storage_resolve_200_response_anyOf_anyOf_1_read_personal_value(
                        required = True, 
                        default_enabled = True, )
                    },
        )
        """

    def testStorageResolve200ResponseAnyOfAnyOf1WriteCredentials(self):
        """Test StorageResolve200ResponseAnyOfAnyOf1WriteCredentials"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
