# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.claim_hook_delete_claim_hook_request import ClaimHookDeleteClaimHookRequest

class TestClaimHookDeleteClaimHookRequest(unittest.TestCase):
    """ClaimHookDeleteClaimHookRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClaimHookDeleteClaimHookRequest:
        """Test ClaimHookDeleteClaimHookRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClaimHookDeleteClaimHookRequest`
        """
        model = ClaimHookDeleteClaimHookRequest()
        if include_optional:
            return ClaimHookDeleteClaimHookRequest(
                id = ''
            )
        else:
            return ClaimHookDeleteClaimHookRequest(
                id = '',
        )
        """

    def testClaimHookDeleteClaimHookRequest(self):
        """Test ClaimHookDeleteClaimHookRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
