# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workflows_participate_in_exchange200_response_verifiable_presentation_request import WorkflowsParticipateInExchange200ResponseVerifiablePresentationRequest

class TestWorkflowsParticipateInExchange200ResponseVerifiablePresentationRequest(unittest.TestCase):
    """WorkflowsParticipateInExchange200ResponseVerifiablePresentationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowsParticipateInExchange200ResponseVerifiablePresentationRequest:
        """Test WorkflowsParticipateInExchange200ResponseVerifiablePresentationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowsParticipateInExchange200ResponseVerifiablePresentationRequest`
        """
        model = WorkflowsParticipateInExchange200ResponseVerifiablePresentationRequest()
        if include_optional:
            return WorkflowsParticipateInExchange200ResponseVerifiablePresentationRequest(
                query = [
                    openapi_client.models.workflows_participate_in_exchange_200_response_verifiable_presentation_request_query_inner.workflows_participateInExchange_200_response_verifiablePresentationRequest_query_inner(
                        type = '', 
                        credential_query = [
                            openapi_client.models.workflows_participate_in_exchange_200_response_verifiable_presentation_request_query_inner_credential_query_inner.workflows_participateInExchange_200_response_verifiablePresentationRequest_query_inner_credentialQuery_inner(
                                required = True, 
                                reason = '', )
                            ], )
                    ],
                challenge = '',
                domain = ''
            )
        else:
            return WorkflowsParticipateInExchange200ResponseVerifiablePresentationRequest(
                query = [
                    openapi_client.models.workflows_participate_in_exchange_200_response_verifiable_presentation_request_query_inner.workflows_participateInExchange_200_response_verifiablePresentationRequest_query_inner(
                        type = '', 
                        credential_query = [
                            openapi_client.models.workflows_participate_in_exchange_200_response_verifiable_presentation_request_query_inner_credential_query_inner.workflows_participateInExchange_200_response_verifiablePresentationRequest_query_inner_credentialQuery_inner(
                                required = True, 
                                reason = '', )
                            ], )
                    ],
                challenge = '',
                domain = '',
        )
        """

    def testWorkflowsParticipateInExchange200ResponseVerifiablePresentationRequest(self):
        """Test WorkflowsParticipateInExchange200ResponseVerifiablePresentationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
