# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.boost_get_boost_recipients200_response_inner_to_any_of1_display import BoostGetBoostRecipients200ResponseInnerToAnyOf1Display

class TestBoostGetBoostRecipients200ResponseInnerToAnyOf1Display(unittest.TestCase):
    """BoostGetBoostRecipients200ResponseInnerToAnyOf1Display unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BoostGetBoostRecipients200ResponseInnerToAnyOf1Display:
        """Test BoostGetBoostRecipients200ResponseInnerToAnyOf1Display
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BoostGetBoostRecipients200ResponseInnerToAnyOf1Display`
        """
        model = BoostGetBoostRecipients200ResponseInnerToAnyOf1Display()
        if include_optional:
            return BoostGetBoostRecipients200ResponseInnerToAnyOf1Display(
                background_color = '',
                background_image = '',
                fade_background_image = True,
                repeat_background_image = True,
                font_color = '',
                accent_color = '',
                accent_font_color = '',
                id_background_image = '',
                fade_id_background_image = True,
                id_background_color = '',
                repeat_id_background_image = True
            )
        else:
            return BoostGetBoostRecipients200ResponseInnerToAnyOf1Display(
        )
        """

    def testBoostGetBoostRecipients200ResponseInnerToAnyOf1Display(self):
        """Test BoostGetBoostRecipients200ResponseInnerToAnyOf1Display"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
