# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.contracts_add_auto_boosts_to_contract_request_autoboosts_inner import ContractsAddAutoBoostsToContractRequestAutoboostsInner

class TestContractsAddAutoBoostsToContractRequestAutoboostsInner(unittest.TestCase):
    """ContractsAddAutoBoostsToContractRequestAutoboostsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContractsAddAutoBoostsToContractRequestAutoboostsInner:
        """Test ContractsAddAutoBoostsToContractRequestAutoboostsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContractsAddAutoBoostsToContractRequestAutoboostsInner`
        """
        model = ContractsAddAutoBoostsToContractRequestAutoboostsInner()
        if include_optional:
            return ContractsAddAutoBoostsToContractRequestAutoboostsInner(
                boost_uri = '',
                signing_authority = openapi_client.models.contracts_create_consent_flow_contract_request_autoboosts_inner_signing_authority.contracts_createConsentFlowContract_request_autoboosts_inner_signingAuthority(
                    name = '', 
                    endpoint = '', )
            )
        else:
            return ContractsAddAutoBoostsToContractRequestAutoboostsInner(
                boost_uri = '',
                signing_authority = openapi_client.models.contracts_create_consent_flow_contract_request_autoboosts_inner_signing_authority.contracts_createConsentFlowContract_request_autoboosts_inner_signingAuthority(
                    name = '', 
                    endpoint = '', ),
        )
        """

    def testContractsAddAutoBoostsToContractRequestAutoboostsInner(self):
        """Test ContractsAddAutoBoostsToContractRequestAutoboostsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
