# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.inbox_get_my_inbox_deliveries200_response_records_inner import InboxGetMyInboxDeliveries200ResponseRecordsInner

class TestInboxGetMyInboxDeliveries200ResponseRecordsInner(unittest.TestCase):
    """InboxGetMyInboxDeliveries200ResponseRecordsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InboxGetMyInboxDeliveries200ResponseRecordsInner:
        """Test InboxGetMyInboxDeliveries200ResponseRecordsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InboxGetMyInboxDeliveries200ResponseRecordsInner`
        """
        model = InboxGetMyInboxDeliveries200ResponseRecordsInner()
        if include_optional:
            return InboxGetMyInboxDeliveries200ResponseRecordsInner(
                id = '',
                credential = openapi_client.models.inbox_get_my_inbox_deliveries_200_response_records_inner_credential.inbox_getMyInboxDeliveries_200_response_records_inner_credential(
                    protected = '', 
                    iv = '', 
                    ciphertext = '', 
                    tag = '', 
                    aad = '', 
                    recipients = [
                        openapi_client.models.inbox_get_my_inbox_deliveries_200_response_records_inner_credential_recipients_inner.inbox_getMyInboxDeliveries_200_response_records_inner_credential_recipients_inner(
                            header = openapi_client.models.inbox_get_my_inbox_deliveries_200_response_records_inner_credential_recipients_inner_header.inbox_getMyInboxDeliveries_200_response_records_inner_credential_recipients_inner_header(
                                alg = '', 
                                iv = '', 
                                tag = '', 
                                epk = openapi_client.models.inbox_get_my_inbox_deliveries_200_response_records_inner_credential_recipients_inner_header_epk.inbox_getMyInboxDeliveries_200_response_records_inner_credential_recipients_inner_header_epk(
                                    kty = '', 
                                    crv = '', 
                                    x = '', 
                                    y = '', 
                                    n = '', 
                                    d = '', ), 
                                kid = '', 
                                apv = '', 
                                apu = '', ), 
                            encrypted_key = '', )
                        ], ),
                expires_at = ''
            )
        else:
            return InboxGetMyInboxDeliveries200ResponseRecordsInner(
                id = '',
                credential = openapi_client.models.inbox_get_my_inbox_deliveries_200_response_records_inner_credential.inbox_getMyInboxDeliveries_200_response_records_inner_credential(
                    protected = '', 
                    iv = '', 
                    ciphertext = '', 
                    tag = '', 
                    aad = '', 
                    recipients = [
                        openapi_client.models.inbox_get_my_inbox_deliveries_200_response_records_inner_credential_recipients_inner.inbox_getMyInboxDeliveries_200_response_records_inner_credential_recipients_inner(
                            header = openapi_client.models.inbox_get_my_inbox_deliveries_200_response_records_inner_credential_recipients_inner_header.inbox_getMyInboxDeliveries_200_response_records_inner_credential_recipients_inner_header(
                                alg = '', 
                                iv = '', 
                                tag = '', 
                                epk = openapi_client.models.inbox_get_my_inbox_deliveries_200_response_records_inner_credential_recipients_inner_header_epk.inbox_getMyInboxDeliveries_200_response_records_inner_credential_recipients_inner_header_epk(
                                    kty = '', 
                                    crv = '', 
                                    x = '', 
                                    y = '', 
                                    n = '', 
                                    d = '', ), 
                                kid = '', 
                                apv = '', 
                                apu = '', ), 
                            encrypted_key = '', )
                        ], ),
                expires_at = '',
        )
        """

    def testInboxGetMyInboxDeliveries200ResponseRecordsInner(self):
        """Test InboxGetMyInboxDeliveries200ResponseRecordsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
