# coding: utf-8

"""
    LearnCard Network Profile Service API

    This is the API for interacting with a LearnCard Network Profile Service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.contracts_get_consented_data_for_did_request_query import ContractsGetConsentedDataForDidRequestQuery

class TestContractsGetConsentedDataForDidRequestQuery(unittest.TestCase):
    """ContractsGetConsentedDataForDidRequestQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContractsGetConsentedDataForDidRequestQuery:
        """Test ContractsGetConsentedDataForDidRequestQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContractsGetConsentedDataForDidRequestQuery`
        """
        model = ContractsGetConsentedDataForDidRequestQuery()
        if include_optional:
            return ContractsGetConsentedDataForDidRequestQuery(
                credentials = openapi_client.models.contracts_get_consented_data_for_contract_request_query_credentials.contracts_getConsentedDataForContract_request_query_credentials(
                    categories = {
                        'key' : True
                        }, ),
                personal = {
                    'key' : True
                    },
                id = None
            )
        else:
            return ContractsGetConsentedDataForDidRequestQuery(
        )
        """

    def testContractsGetConsentedDataForDidRequestQuery(self):
        """Test ContractsGetConsentedDataForDidRequestQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
