# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.storage_store_request_item_any_of import StorageStoreRequestItemAnyOf

class TestStorageStoreRequestItemAnyOf(unittest.TestCase):
    """StorageStoreRequestItemAnyOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StorageStoreRequestItemAnyOf:
        """Test StorageStoreRequestItemAnyOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StorageStoreRequestItemAnyOf`
        """
        model = StorageStoreRequestItemAnyOf()
        if include_optional:
            return StorageStoreRequestItemAnyOf(
                context = [
                    null
                    ],
                id = '',
                type = None,
                issuer = None,
                credential_subject = None,
                refresh_service = None,
                credential_schema = None,
                issuance_date = '',
                expiration_date = '',
                credential_status = None,
                name = '',
                description = '',
                valid_from = '',
                valid_until = '',
                status = None,
                terms_of_use = None,
                evidence = None,
                proof = None,
                verifiable_credential = None,
                holder = ''
            )
        else:
            return StorageStoreRequestItemAnyOf(
                context = [
                    null
                    ],
                type = None,
                issuer = None,
                credential_subject = None,
                proof = None,
        )
        """

    def testStorageStoreRequestItemAnyOf(self):
        """Test StorageStoreRequestItemAnyOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
