# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.profile_signing_authority200_response_relationship import ProfileSigningAuthority200ResponseRelationship

class TestProfileSigningAuthority200ResponseRelationship(unittest.TestCase):
    """ProfileSigningAuthority200ResponseRelationship unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileSigningAuthority200ResponseRelationship:
        """Test ProfileSigningAuthority200ResponseRelationship
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileSigningAuthority200ResponseRelationship`
        """
        model = ProfileSigningAuthority200ResponseRelationship()
        if include_optional:
            return ProfileSigningAuthority200ResponseRelationship(
                name = 'p',
                did = '',
                is_primary = True
            )
        else:
            return ProfileSigningAuthority200ResponseRelationship(
                name = 'p',
                did = '',
        )
        """

    def testProfileSigningAuthority200ResponseRelationship(self):
        """Test ProfileSigningAuthority200ResponseRelationship"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
