# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.share_links_api import ShareLinksApi


class TestShareLinksApi(unittest.TestCase):
    """ShareLinksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ShareLinksApi()

    def tearDown(self) -> None:
        pass

    def test_public_share_links_acknowledge_view(self) -> None:
        """Test case for public_share_links_acknowledge_view

        Acknowledge a share view receipt
        """
        pass

    def test_public_share_links_content(self) -> None:
        """Test case for public_share_links_content

        Fetch guarded share content
        """
        pass

    def test_public_share_links_resolve(self) -> None:
        """Test case for public_share_links_resolve

        Resolve public share metadata
        """
        pass

    def test_share_links_create(self) -> None:
        """Test case for share_links_create

        Create an owner share link
        """
        pass

    def test_share_links_get(self) -> None:
        """Test case for share_links_get

        Get owner share-link metadata
        """
        pass

    def test_share_links_get_content(self) -> None:
        """Test case for share_links_get_content

        Get encrypted share content (owner only)
        """
        pass

    def test_share_links_get_operation_status(self) -> None:
        """Test case for share_links_get_operation_status

        Get owner scoped operation status
        """
        pass

    def test_share_links_get_recovery(self) -> None:
        """Test case for share_links_get_recovery

        Get owner-encrypted recovery (owner only)
        """
        pass

    def test_share_links_list(self) -> None:
        """Test case for share_links_list

        List owner share links
        """
        pass

    def test_share_links_retry(self) -> None:
        """Test case for share_links_retry

        Retry an owner operation
        """
        pass

    def test_share_links_revoke(self) -> None:
        """Test case for share_links_revoke

        Revoke an owner share link
        """
        pass

    def test_share_links_update(self) -> None:
        """Test case for share_links_update

        Update an owner share link
        """
        pass


if __name__ == '__main__':
    unittest.main()
