# coding: utf-8

"""
    LearnCard Network Profile Service API

    This is the API for interacting with a LearnCard Network Profile Service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.auth_grants_add_auth_grant_request import AuthGrantsAddAuthGrantRequest

class TestAuthGrantsAddAuthGrantRequest(unittest.TestCase):
    """AuthGrantsAddAuthGrantRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthGrantsAddAuthGrantRequest:
        """Test AuthGrantsAddAuthGrantRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthGrantsAddAuthGrantRequest`
        """
        model = AuthGrantsAddAuthGrantRequest()
        if include_optional:
            return AuthGrantsAddAuthGrantRequest(
                name = '',
                description = '',
                challenge = 'auth-grant:0123456789',
                status = 'revoked',
                scope = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return AuthGrantsAddAuthGrantRequest(
        )
        """

    def testAuthGrantsAddAuthGrantRequest(self):
        """Test AuthGrantsAddAuthGrantRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
