# coding: utf-8

"""
    LearnCard Network Profile Service API

    This is the API for interacting with a LearnCard Network Profile Service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.profile_generate_invite200_response import ProfileGenerateInvite200Response

class TestProfileGenerateInvite200Response(unittest.TestCase):
    """ProfileGenerateInvite200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProfileGenerateInvite200Response:
        """Test ProfileGenerateInvite200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProfileGenerateInvite200Response`
        """
        model = ProfileGenerateInvite200Response()
        if include_optional:
            return ProfileGenerateInvite200Response(
                profile_id = '',
                challenge = '',
                expires_in = 1.337
            )
        else:
            return ProfileGenerateInvite200Response(
                profile_id = '',
                challenge = '',
                expires_in = 1.337,
        )
        """

    def testProfileGenerateInvite200Response(self):
        """Test ProfileGenerateInvite200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
