name: 'Setup Bun and Install Dependencies'
description: 'A composite action to set up the environment for CI/CD jobs.'

runs:
    using: 'composite'
    steps:
        - name: Setup Bun
          uses: oven-sh/setup-bun@v2

        - name: Setup Bun cache
          uses: actions/cache@v6
          with:
              path: ~/.bun/install/cache
              key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
              restore-keys: |
                  ${{ runner.os }}-bun-

        - name: Disable optional MongoDB binary download
          shell: bash
          run: echo "MONGOMS_DISABLE_POSTINSTALL=1" >> "$GITHUB_ENV"

        - name: Install dependencies
          shell: bash
          run: bun install --frozen-lockfile
