name: 'Setup Node.js, pnpm, and Install Dependencies'
description: 'A composite action to set up the environment for CI/CD jobs.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js 20.10
      uses: actions/setup-node@v4
      with:
        node-version: 20.10.0

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --no-frozen-lockfile
