packages:
  - 'docs'
  - 'examples/*'
  - 'packages/*'
  - 'packages/learn-card-network/*'
  - 'packages/plugins/*'
  - 'services/*'
  - 'services/learn-card-network/*'
  - 'apps/*'
  - 'tests/*'
  - 'tools/executors/workspace/*'
