(function(){var cfg=window.__LC_EMBED__||{};var root=document.getElementById('root');if(!root)return;
var S={view:(cfg.loggedInEmail?'accept':'email'),email:(cfg.loggedInEmail||''),code:'',consent:false,error:'',pending:false,usedEmailFlow:!cfg.loggedInEmail};
function clr(el){while(el.firstChild)el.removeChild(el.firstChild);}
function txt(t){return document.createTextNode(t);}
function mk(tag,attrs,kids){var n=document.createElement(tag);if(attrs){for(var k in attrs){var v=attrs[k];if(k==='class')n.className=v;else if(k==='for')n.htmlFor=v;else if(k==='text')n.textContent=v;else if(k==='onClick')n.addEventListener('click',v);else if(k==='onInput')n.addEventListener('input',v);else if(k==='onChange')n.addEventListener('change',v);else if(k==='disabled')n.disabled=!!v;else if(k==='checked')n.checked=!!v;else if(v!=null)n.setAttribute(k,String(v));}}if(kids&&kids.length){for(var i=0;i<kids.length;i++){var c=kids[i];if(c==null)continue;n.appendChild(typeof c==='string'?txt(c):c);}}return n;}
function validEmail(v){if(typeof v!=='string')return false;var s=v.trim();if(!s)return false;try{var inp=document.createElement('input');inp.type='email';inp.value=s;return inp.checkValidity();}catch(e){return/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);}}
function send(type,payload){try{if(!cfg.parentOrigin)return;window.parent.postMessage({__lcEmbed:true,type:type,nonce:cfg.nonce,payload:payload},cfg.parentOrigin);}catch(e){}}
function trusted(data,type){return data&&typeof data==='object'&&data.__lcEmbed===true&&data.type===type&&data.nonce===cfg.nonce;}
function Stepper(step){var dots=[];for(var i=1;i<=3;i++){var cls='lc-dot';if(i<step)cls+=' done';else if(i===step)cls+=' active';dots.push(mk('div',{class:cls},[]));if(i<3){var bc='lc-bar';if(i<step)bc+=' done';dots.push(mk('div',{class:bc},[]));}}return mk('div',{class:'lc-stepper'},dots);}
function CredCard(){var nm=cfg.credentialName||'Credential';var is=cfg.partnerName||cfg.partnerLabel||'';return mk('div',{class:'cred-card'},[mk('div',{class:'cred-card-label'},[txt('Credential')]),mk('div',{class:'cred-card-name'},[txt(nm)]),is?mk('div',{class:'cred-card-issuer'},[txt('Issued by '+is)]):null]);}
function Footer(){var lu=cfg.logoUrl||'';var lockSvg=document.createElementNS('http://www.w3.org/2000/svg','svg');lockSvg.setAttribute('viewBox','0 0 24 24');lockSvg.setAttribute('fill','#c0c8d0');lockSvg.style.cssText='width:10px;height:10px;flex-shrink:0;';var lockPath=document.createElementNS('http://www.w3.org/2000/svg','path');lockPath.setAttribute('d','M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2z');lockSvg.appendChild(lockPath);var f=mk('div',{class:'lc-footer'},[]);f.appendChild(lockSvg);f.appendChild(txt('Secured by '));if(lu){var img=document.createElement('img');img.src=lu;img.alt='LearnCard';f.appendChild(img);}else{f.appendChild(txt('LearnCard'));}return f;}
function spinner(){var s=document.createElementNS('http://www.w3.org/2000/svg','svg');s.setAttribute('class','spinner');s.setAttribute('viewBox','0 0 24 24');s.setAttribute('fill','none');s.setAttribute('stroke','currentColor');s.setAttribute('stroke-width','2.5');var c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('cx','12');c.setAttribute('cy','12');c.setAttribute('r','10');c.setAttribute('stroke-dasharray','42');c.setAttribute('stroke-dashoffset','14');c.setAttribute('stroke-linecap','round');s.appendChild(c);return s;}
function btnLoad(btn,t){btn.disabled=true;btn.classList.add('loading');btn.textContent='';btn.appendChild(spinner());btn.appendChild(txt(t));}
function otpInputs(value,onInput){var wrap=mk('div',{class:'otp'},[]);var digits=(value||'').split('');function setD(i,v){digits[i]=v||'';onInput(digits.join(''));}function focI(i){var ins=wrap.querySelectorAll('input');if(ins[i])ins[i].focus();}for(var i=0;i<6;i++){(function(idx){var inp=mk('input',{type:'text',inputMode:'numeric',maxLength:1,value:digits[idx]||''},[]);inp.addEventListener('input',function(e){var v=e.target.value.replace(/[^0-9]/g,'').slice(0,1);e.target.value=v;setD(idx,v);if(v){e.target.classList.add('filled');if(idx<5)focI(idx+1);}else{e.target.classList.remove('filled');if(idx>0)focI(idx-1);}});inp.addEventListener('paste',function(e){e.preventDefault();var p=(e.clipboardData||window.clipboardData).getData('text').replace(/[^0-9]/g,'').slice(0,6);if(!p)return;var ins=wrap.querySelectorAll('input');for(var j=0;j<p.length&&j<6;j++){digits[j]=p[j];if(ins[j]){ins[j].value=p[j];ins[j].classList.add('filled');}}onInput(digits.join(''));focI(Math.min(p.length,5));});inp.addEventListener('keydown',function(e){if(e.key==='Backspace'&&!e.target.value&&idx>0)focI(idx-1);});if(digits[idx])inp.className='filled';wrap.appendChild(inp);})(i);}return wrap;}
var confColors=['#2EC4A5','#f59e0b','#8b5cf6','#ef4444','#3b82f6','#ec4899','#10b981','#06b6d4','#f43f5e','#fbbf24','#a78bfa','#34d399'];
var confShapes=[{w:8,h:8,r:2},{w:6,h:10,r:2},{w:10,h:6,r:2},{w:7,h:7,r:50},{w:5,h:5,r:50}];
function confetti(c){for(var i=0;i<24;i++){var p=document.createElement('div');p.className='confetti-piece';var col=confColors[Math.floor(Math.random()*confColors.length)];var sh=confShapes[Math.floor(Math.random()*confShapes.length)];var l=(Math.random()*90+5);var d=(Math.random()*0.4);var dur=(2.0+Math.random()*1.2);var rot=(540+Math.random()*540);p.style.cssText='left:'+l+'%;background:'+col+';width:'+sh.w+'px;height:'+sh.h+'px;border-radius:'+sh.r+'%;--delay:'+d+'s;--duration:'+dur+'s;--rotation:'+rot+'deg;';c.appendChild(p);}}
function EmailView(){var ei;return mk('div',{id:'view-email'},[Stepper(1),CredCard(),mk('div',{class:'view-content'},[mk('div',{class:'field'},[mk('label',{class:'label',for:'email'},[txt('Email address')]),(function(){ei=mk('input',{id:'email',class:'input',type:'email',placeholder:'you@example.com',autocomplete:'email',value:S.email},[]);ei.addEventListener('input',function(e){S.email=e.target.value;var b=document.getElementById('send');if(b)b.disabled=!validEmail((S.email||'').trim())||!!S.pending;if(S.error){S.error='';var err=document.getElementById('error');if(err)err.textContent='';}});ei.addEventListener('keydown',function(e){if(e.key==='Enter'){var b=document.getElementById('send');if(b&&!b.disabled)b.click();}});return ei;})()]),mk('button',{id:'send',class:'btn btn-primary',disabled:!validEmail((S.email||'').trim())||!!S.pending,onClick:function(){var em=(S.email||'').trim();if(!validEmail(em)){S.error='Please enter a valid email.';render();return;}S.error='';S.pending=true;var b=document.getElementById('send');if(b)btnLoad(b,'Sending...');send('lc-embed:email-submit',{email:em});}},[txt('Send Code \u2192')]),mk('div',{class:'error',id:'error'},[txt(S.error||'')])])]);}
function OtpView(){var cw=otpInputs(S.code,function(v){S.code=v;var vb=document.getElementById('verify');if(vb)vb.disabled=(S.code.length!==6)||!!S.pending;if(S.error&&S.code.length>0){S.error='';var err=document.getElementById('error');if(err)err.textContent='';}});return mk('div',{id:'view-otp'},[Stepper(2),mk('div',{class:'view-content'},[mk('div',{class:'title'},[txt('Enter verification code')]),mk('div',{class:'subtitle'},[txt('We sent a code to '),mk('strong',null,[txt(S.email)]),txt('. It expires in 10 minutes.')]),cw,mk('button',{id:'verify',class:'btn btn-primary',disabled:S.code.length!==6||!!S.pending,onClick:function(){if(S.code.length!==6){S.error='Enter the 6-digit code.';render();return;}S.error='';S.pending=true;var b=document.getElementById('verify');if(b)btnLoad(b,'Verifying...');send('lc-embed:otp-verify',{email:S.email,code:S.code});}},[txt('Verify')]),mk('div',{class:'error',id:'error'},[txt(S.error||'')]),mk('div',{class:'hint'},[txt("Didn't get it? Check spam or try again.")])])]);}
function AcceptView(){return mk('div',{id:'view-accept'},[CredCard(),mk('div',{class:'view-content'},[mk('div',{class:'subtitle',style:'margin-top: 8px'},[txt('Signed in as '),mk('strong',null,[txt(S.email)])]),mk('button',{id:'accept',class:'btn btn-primary',disabled:!!S.pending,onClick:function(){S.error='';S.pending=true;var b=document.getElementById('accept');if(b)btnLoad(b,'Claiming...');send('lc-embed:accept',{email:S.email});}},[txt('Accept Credential \u2192')]),mk('button',{id:'logout',class:'btn btn-secondary',disabled:!!S.pending,onClick:function(){S.error='';S.pending=true;render();send('lc-embed:logout',{});}},[txt('Use a different email')]),mk('div',{class:'error',id:'error'},[txt(S.error||'')])])]);}
function SuccessView(){var ss=S.usedEmailFlow;var cw=null;if(cfg.showConsent){var ch=mk('input',{id:'consent',type:'checkbox'},[]);ch.checked=!!S.consent;ch.addEventListener('change',function(e){S.consent=!!e.target.checked;});cw=mk('label',{class:'consent-row',id:'consent-wrap'},[ch,mk('span',null,[txt('Allow '+(cfg.partnerName||cfg.partnerLabel||'')+' to automatically add future credentials to my LearnCard.')])]);}
var cs=document.createElementNS('http://www.w3.org/2000/svg','svg');cs.setAttribute('viewBox','0 0 24 24');cs.setAttribute('fill','none');cs.setAttribute('stroke','#10b981');cs.setAttribute('stroke-width','2.5');cs.style.cssText='width:36px;height:36px;';var cp=document.createElementNS('http://www.w3.org/2000/svg','path');cp.setAttribute('class','checkmark-path');cp.setAttribute('d','M20 6L9 17l-5-5');cp.setAttribute('stroke-linecap','round');cp.setAttribute('stroke-linejoin','round');cs.appendChild(cp);
var cc=mk('div',{class:'confetti-container'},[]);var kids=[];if(ss)kids.push(Stepper(3));kids.push(cc);kids.push(mk('div',{class:'view-content'},[mk('div',{class:'success'},[mk('div',{class:'success-circle'},[cs]),mk('div',{class:'title'},[txt('Credential Claimed!')]),mk('div',{class:'subtitle'},[txt('Your credential has been securely added to your LearnCard wallet.')]),cw,mk('button',{id:'viewWallet',class:'btn btn-primary',onClick:function(){var payload={__lcEmbed:true,type:'lc-embed:complete',nonce:cfg.nonce,payload:{credentialId:'temp-'+Date.now(),consentGiven:!!S.consent}};if(!cfg.parentOrigin)return;window.parent.postMessage(payload,cfg.parentOrigin);}},[txt('View My LearnCard')])])]));var ve=mk('div',{id:'view-success'},kids);setTimeout(function(){confetti(cc);},100);return ve;}
window.addEventListener('message',function(ev){var data=ev.data;
if(trusted(data,'lc-embed:email-submit:result')){S.pending=false;if(data.payload&&data.payload.ok){S.view='otp';S.error='';}else{S.error=(data.payload&&data.payload.error)||'Failed to send code.';}render();return;}
if(trusted(data,'lc-embed:otp-verify:result')){S.pending=false;if(data.payload&&data.payload.ok){S.view='success';S.error='';}else{S.error=(data.payload&&data.payload.error)||'Verification failed.';}render();return;}
if(trusted(data,'lc-embed:accept:result')){S.pending=false;if(data.payload&&data.payload.ok){S.view='success';S.error='';}else{S.error=(data.payload&&data.payload.error)||'Failed to claim credential.';}render();return;}
if(trusted(data,'lc-embed:logout:result')){S.pending=false;S.view='email';S.email='';S.code='';S.error='';S.usedEmailFlow=true;render();return;}});
var curView=null;
function render(){var ve=S.view==='email'?EmailView():S.view==='otp'?OtpView():S.view==='accept'?AcceptView():SuccessView();var wrap=mk('div',{class:'wrap'},[]);var vw=mk('div',{class:'view-wrap'},[ve]);wrap.appendChild(vw);wrap.appendChild(Footer());if(curView&&curView!==S.view){var old=root.firstChild;if(old){var ovw=old.querySelector('.view-wrap');if(ovw){ovw.classList.add('exiting');setTimeout(function(){clr(root);vw.classList.add('entering');root.appendChild(wrap);void vw.offsetWidth;vw.classList.remove('entering');},200);curView=S.view;return;}}}clr(root);root.appendChild(wrap);curView=S.view;}
render();})();
