#############################################
##  Configuration for Netlify deployments  ##
#############################################

[build.environment]
NPM_FLAGS = "--version"
# Global Context Default
[build]
command = "npx pnpm install -P false --store=node_modules/.pnpm-store && npx pnpm build"
publish = "dist/"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
