#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../semver@5.7.1/node_modules/semver/bin/semver" "$@"
else
  exec node  "$basedir/../../../../../semver@5.7.1/node_modules/semver/bin/semver" "$@"
fi
