/**
 * WalletEvent — the unified event stream that feeds pathway progress.
 *
 * ## Why a single event union
 *
 * The app has many surfaces that conclude with "something happened
 * that should count toward a pathway node":
 *
 *   - A learner claims a boost (`ClaimBoost`, `InteractionsPage`).
 *   - A VC-API request completes (`ClaimFromRequest`,
 *     `ExchangeAcceptCredentials`).
 *   - A partner app calls `saveCredential` through the postMessage
 *     SDK (`useLearnCardMessageHandlers`).
 *   - A consent-flow sync pulls in a fresh credential in the
 *     background.
 *   - An AI tutor session ends (`FinishSessionButton`,
 *     `finishSession` in the chat nanostore).
 *   - Future: artifact uploads, self-attest confirmations, endorsement
 *     arrivals — each a different upstream, each eventually
 *     interesting to the pathway reactor.
 *
 * Without a single event seam, every new completion-source has to
 * know about every consumer (pathway progress, analytics, in-wallet
 * caches). That's N×M coupling. One event bus means every source
 * pushes into one place and every consumer subscribes to the same
 * place — N+M.
 *
 * ## Why zod schemas (and not just TypeScript types)
 *
 * Two of the event fields cross process boundaries as the sync story
 * matures — cross-device replay, offline queueing, server-mirrored
 * event log. Runtime validation at publish time catches corrupted or
 * stale events *before* they reach the reactor, which is the most
 * expensive consumer. Cheap insurance; parse once at the bus seam.
 *
 * The schemas are deliberately liberal on the `vc` payload — we
 * accept any object and only constrain the fields the matcher
 * actually reads. A stricter `VcSchema` would reject legitimate
 * real-world credentials (unexpected extra fields, non-conformant
 * issuer shapes) that the `VcLike` matcher (`core/outcomeMatcher`)
 * handles gracefully.
 */

import { z } from 'zod';

// ---------------------------------------------------------------------------
// Source provenance — who / what surfaced the event.
// ---------------------------------------------------------------------------

/**
 * Where in the app a `CredentialIngested` originated. Surfaces use
 * this for analytics attribution and for UX choices — the post-claim
 * "this advanced your pathway" banner is only meaningful for
 * foreground claims, not for background consent-flow sync.
 *
 * `unknown` is explicitly allowed so unsurveyed call sites stay
 * honest; we'd rather have a well-formed event with `unknown` source
 * than a silently dropped one.
 */
export const CredentialIngestSourceSchema = z.enum([
    'claim-link',
    'claim-raw',
    'dashboard',
    'vc-api-request',
    'vc-api-exchange',
    'partner-sdk',
    'consent-flow',
    'interactions',
    'notifications',
    'self-issued',
    'import',
    'replay',
    'unknown',
]);
export type CredentialIngestSource = z.infer<typeof CredentialIngestSourceSchema>;

/**
 * Where an `AiSessionCompleted` originated. We separate `finish`
 * (explicit learner action) from `auto-end` (service-side timeout /
 * summary-ready) because the right post-completion UX differs —
 * finish earns a celebratory toast, auto-end shouldn't.
 */
export const AiSessionEndSourceSchema = z.enum([
    'user-finish',
    'auto-end',
    'replay',
]);
export type AiSessionEndSource = z.infer<typeof AiSessionEndSourceSchema>;

// ---------------------------------------------------------------------------
// CredentialIngested — a VC just became available in the wallet.
// ---------------------------------------------------------------------------

/**
 * Loose VC envelope. See the module docstring for why this is not
 * strictly validated here; the matcher (`VcLike`) is the schema of
 * record for what fields actually get read.
 */
const VcPayloadSchema = z.record(z.string(), z.unknown());

export const CredentialIngestedEventSchema = z.object({
    kind: z.literal('credential-ingested'),

    /**
     * Monotonic event id. Generated by the publisher; the bus does
     * not assign ids. Used for dedup and for correlating the event
     * with downstream proposals (each proposal tags the `eventId`
     * that spawned it).
     */
    eventId: z.string().uuid(),

    /** Wallet storage URI. The stable identity of this credential. */
    credentialUri: z.string().min(1),

    /**
     * Wallet-local index record id. Optional because not every ingest
     * path surfaces it (partner-SDK `saveCredential` returns only a
     * URI). Downstream consumers that need it can look it up by URI.
     */
    recordId: z.string().optional(),

    /**
     * The VC body as a plain JSON object. The matcher reads a small
     * fixed subset (`type`, `issuer`, `credentialSubject`, …) — see
     * `VcLike`.
     */
    vc: VcPayloadSchema,

    /** ISO timestamp the credential became available to the wallet. */
    ingestedAt: z.string().datetime(),

    source: CredentialIngestSourceSchema,

    /**
     * Optional provenance hints populated by sources that know more
     * than the raw VC. These short-circuit extraction work in the
     * identity layer and give us reliable fingerprints when the VC
     * itself is ambiguous (e.g. a bare-minimum OBv3 badge whose
     * `type` is just `OpenBadgeCredential`).
     */
    boostUri: z.string().optional(),
    contractUri: z.string().optional(),
});
export type CredentialIngestedEvent = z.infer<typeof CredentialIngestedEventSchema>;

// ---------------------------------------------------------------------------
// AiSessionCompleted — a first-party tutor session ended.
// ---------------------------------------------------------------------------

export const AiSessionCompletedEventSchema = z.object({
    kind: z.literal('ai-session-completed'),

    eventId: z.string().uuid(),

    /** Chat thread id. Stable across refreshes; used for dedup. */
    threadId: z.string().min(1),

    /**
     * Topic boost URI the session ran against. Optional because the
     * onboarding / skill-profile flow runs sessions without a
     * resolvable topic; those events fire, they just don't match
     * any termination.
     */
    topicUri: z.string().optional(),

    /**
     * AI Learning Pathway boost URI the session followed (not the
     * containing LearnCard pathway). Optional.
     */
    aiPathwayUri: z.string().optional(),

    /** ISO timestamp when the session ended. */
    endedAt: z.string().datetime(),

    /**
     * Optional duration hint; publishers that track session length
     * (chat store) pass it through so termination kinds that want
     * "≥ N minutes on topic" can reason about it later.
     */
    durationSec: z.number().nonnegative().optional(),

    source: AiSessionEndSourceSchema,
});
export type AiSessionCompletedEvent = z.infer<typeof AiSessionCompletedEventSchema>;

// ---------------------------------------------------------------------------
// Union + helpers
// ---------------------------------------------------------------------------

export const WalletEventSchema = z.discriminatedUnion('kind', [
    CredentialIngestedEventSchema,
    AiSessionCompletedEventSchema,
]);
export type WalletEvent = z.infer<typeof WalletEventSchema>;

/**
 * Type guard helper for reactor branches. Prefer this over
 * `event.kind === 'credential-ingested'` inline so the narrowing
 * logic stays colocated with the schema definition.
 */
export const isCredentialIngested = (
    event: WalletEvent,
): event is CredentialIngestedEvent => event.kind === 'credential-ingested';

export const isAiSessionCompleted = (
    event: WalletEvent,
): event is AiSessionCompletedEvent => event.kind === 'ai-session-completed';

export const WALLET_EVENT_KINDS = [
    'credential-ingested',
    'ai-session-completed',
] as const satisfies ReadonlyArray<WalletEvent['kind']>;
