/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function getVersion(a: number): void;
export function resolveDID(a: number, b: number, c: number, d: number): number;
export function generateEd25519Key(a: number): void;
export function generateEd25519KeyFromBytes(a: number, b: number, c: number): void;
export function generateSecp256k1Key(a: number): void;
export function generateSecp256k1KeyFromBytes(a: number, b: number, c: number): void;
export function keyToDID(a: number, b: number, c: number, d: number, e: number): void;
export function keyToVerificationMethod(a: number, b: number, c: number, d: number): number;
export function issueCredential(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function prepareIssueCredential(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function completeIssueCredential(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function verifyCredential(a: number, b: number, c: number, d: number): number;
export function issuePresentation(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function prepareIssuePresentation(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function completeIssuePresentation(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function verifyPresentation(a: number, b: number, c: number, d: number): number;
export function DIDAuth(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function JWKFromTezos(a: number, b: number): number;
export function delegateCapability(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function prepareDelegateCapability(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function completeDelegateCapability(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function verifyDelegation(a: number, b: number): number;
export function invokeCapability(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function prepareInvokeCapability(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function completeInvokeCapability(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function verifyInvocationSignature(a: number, b: number): number;
export function verifyInvocation(a: number, b: number, c: number, d: number): number;
export function contextLoader(a: number, b: number): number;
export function didkit_error_message(): number;
export function didkit_error_code(): number;
export function SHA1DCUpdate(a: number, b: number, c: number): void;
export function sha1_compression_states(a: number, b: number, c: number, d: number): void;
export function SHA1DCInit(a: number): void;
export function SHA1DCSetSafeHash(a: number, b: number): void;
export function SHA1DCSetUseUBC(a: number, b: number): void;
export function SHA1DCSetUseDetectColl(a: number, b: number): void;
export function SHA1DCSetDetectReducedRoundCollision(a: number, b: number): void;
export function SHA1DCSetCallback(a: number, b: number): void;
export function ubc_check(a: number, b: number): void;
export function SHA1DCFinal(a: number, b: number): number;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h47a829c6210a1ab1(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h68d8a804a96909b8(a: number, b: number, c: number, d: number): void;
