/**
 * Shared tenant resolution for Netlify Edge Functions.
 *
 * Imports a single generated JSON (produced by scripts/generate-edge-tenant-configs.ts)
 * that contains the tenant registry and every per-tenant config file, pre-bundled.
 * Adding a new tenant or stage config just means adding files under environments/ and
 * re-running the generator — no manual imports or registration needed.
 *
 * Exports:
 *   resolveTenantConfig(hostname)  — full merged config for the hostname
 *   getTenantEntry(hostname)       — raw registry entry (tenantId, domain)
 *   getStageFromHostname(hostname) — e.g. "alpha" from "alpha.vetpass.app"
 *   getTenantOrigin(requestUrl)    — protocol + host, e.g. "https://alpha.vetpass.app"
 */

import { deepMerge } from './deep-merge.ts';

// @ts-expect-error — Deno JSON import assertion; generated by scripts/generate-edge-tenant-configs.ts
import generatedData from './resolved-tenant-configs.generated.json' assert { type: 'json' };

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface TenantEntry {
    tenantId: string;
    domain: string;
    configOverrides?: Record<string, unknown>;
}

export interface TenantRegistry {
    hostnames: Record<string, TenantEntry>;
    defaultTenant: TenantEntry;
}

/** Resolved config — typed loosely since we merge arbitrary JSON. */
export type ResolvedTenantConfig = Record<string, unknown>;

interface TenantConfigSet {
    base: Record<string, unknown>;
    stages: Record<string, Record<string, unknown>>;
}

// ---------------------------------------------------------------------------
// Internal data structures (from generated JSON)
// ---------------------------------------------------------------------------

const registry: TenantRegistry = generatedData.registry as TenantRegistry;
const tenantConfigSets: Record<string, TenantConfigSet> = generatedData.tenants as Record<string, TenantConfigSet>;

// ---------------------------------------------------------------------------
// Public helpers
// ---------------------------------------------------------------------------

/**
 * Look up the raw registry entry for a hostname.
 * Falls back to `defaultTenant` if the hostname isn't registered.
 */
export function getTenantEntry(hostname: string): TenantEntry {
    return registry.hostnames[hostname] ?? registry.defaultTenant;
}

/**
 * Derive the stage name from a hostname.
 *
 * Examples:
 *   "alpha.vetpass.app"   → "alpha"
 *   "staging.learncard.ai" → "staging"
 *   "learncard.app"       → null  (production, no stage prefix)
 *   "localhost"            → null
 */
export function getStageFromHostname(hostname: string): string | null {
    // localhost is always "local" stage
    if (hostname.startsWith('localhost') || hostname.startsWith('127.0.0.1')) {
        return 'local';
    }

    const parts = hostname.split('.');

    // 3+ parts and the first part isn't "www" → treat it as a stage
    if (parts.length >= 3 && parts[0] !== 'www') {
        return parts[0];
    }

    return null;
}

/**
 * Resolve the full tenant config for a hostname by:
 *   1. Looking up the tenantId in the registry
 *   2. Loading the base config for that tenant
 *   3. Deep-merging the stage-specific config (if any)
 *   4. Applying registry configOverrides on top (if any)
 */
export function resolveTenantConfig(hostname: string): ResolvedTenantConfig {
    const entry = getTenantEntry(hostname);
    const configSet = tenantConfigSets[entry.tenantId];

    if (!configSet) {
        // Unknown tenant — return just registry-level data
        return {
            tenantId: entry.tenantId,
            domain: entry.domain,
            ...(entry.configOverrides ?? {}),
        };
    }

    const stage = getStageFromHostname(hostname);
    const stageConfig = stage && configSet.stages[stage] ? configSet.stages[stage] : {};

    // base ← stage ← registry configOverrides
    let merged = deepMerge(configSet.base, stageConfig);

    if (entry.configOverrides) {
        merged = deepMerge(merged, entry.configOverrides);
    }

    return merged;
}

/**
 * Extract the origin (protocol + host) from a full URL.
 * Falls back to "https://learncard.app" on parse failure.
 */
export function getTenantOrigin(requestUrl: string): string {
    try {
        const url = new URL(requestUrl);
        return `${url.protocol}//${url.host}`;
    } catch {
        return 'https://learncard.app';
    }
}
