/*
 * LearnCloud Network API
 * API for interacting with LearnCloud Network
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.BoostSendBoostRequestCredentialAnyOfIssuerAnyOfType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf
 */
public class BoostSendBoostRequestCredentialAnyOfEvidenceAnyOfTest {
    private final BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf model = new BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf();

    /**
     * Model tests for BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf
     */
    @Test
    public void testBoostSendBoostRequestCredentialAnyOfEvidenceAnyOf() {
        // TODO: test BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
