/*
 * LearnCloud Network API
 * API for interacting with LearnCloud Network
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ContractsGetTermsTransactionHistoryRequestQueryDateAnyOfAnyOf
 */
public class ContractsGetTermsTransactionHistoryRequestQueryDateAnyOfAnyOfTest {
    private final ContractsGetTermsTransactionHistoryRequestQueryDateAnyOfAnyOf model = new ContractsGetTermsTransactionHistoryRequestQueryDateAnyOfAnyOf();

    /**
     * Model tests for ContractsGetTermsTransactionHistoryRequestQueryDateAnyOfAnyOf
     */
    @Test
    public void testContractsGetTermsTransactionHistoryRequestQueryDateAnyOfAnyOf() {
        // TODO: test ContractsGetTermsTransactionHistoryRequestQueryDateAnyOfAnyOf
    }

    /**
     * Test the property '$gt'
     */
    @Test
    public void $gtTest() {
        // TODO: test $gt
    }

}
