/*
 * LearnCloud Network API
 * API for interacting with LearnCloud Network
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ContractsGetTermsTransactionHistoryRequestQueryDateAnyOf;
import org.openapitools.client.model.ContractsGetTermsTransactionHistoryRequestQueryDateAnyOf1;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ContractsGetTermsTransactionHistoryRequestQueryDate
 */
public class ContractsGetTermsTransactionHistoryRequestQueryDateTest {
    private final ContractsGetTermsTransactionHistoryRequestQueryDate model = new ContractsGetTermsTransactionHistoryRequestQueryDate();

    /**
     * Model tests for ContractsGetTermsTransactionHistoryRequestQueryDate
     */
    @Test
    public void testContractsGetTermsTransactionHistoryRequestQueryDate() {
        // TODO: test ContractsGetTermsTransactionHistoryRequestQueryDate
    }

    /**
     * Test the property '$gt'
     */
    @Test
    public void $gtTest() {
        // TODO: test $gt
    }

    /**
     * Test the property '$lt'
     */
    @Test
    public void $ltTest() {
        // TODO: test $lt
    }

    /**
     * Test the property '$eq'
     */
    @Test
    public void $eqTest() {
        // TODO: test $eq
    }

}
