/*
 * LearnCloud Network API
 * API for interacting with LearnCloud Network
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ProfileSigningAuthorities200ResponseInnerRelationship;
import org.openapitools.client.model.ProfileSigningAuthorities200ResponseInnerSigningAuthority;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProfileSigningAuthorities200ResponseInner
 */
public class ProfileSigningAuthorities200ResponseInnerTest {
    private final ProfileSigningAuthorities200ResponseInner model = new ProfileSigningAuthorities200ResponseInner();

    /**
     * Model tests for ProfileSigningAuthorities200ResponseInner
     */
    @Test
    public void testProfileSigningAuthorities200ResponseInner() {
        // TODO: test ProfileSigningAuthorities200ResponseInner
    }

    /**
     * Test the property 'signingAuthority'
     */
    @Test
    public void signingAuthorityTest() {
        // TODO: test signingAuthority
    }

    /**
     * Test the property 'relationship'
     */
    @Test
    public void relationshipTest() {
        // TODO: test relationship
    }

}
