/*
 * LearnCloud Network API
 * API for interacting with LearnCloud Network
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProfileManagerGetProfileManager200Response
 */
public class ProfileManagerGetProfileManager200ResponseTest {
    private final ProfileManagerGetProfileManager200Response model = new ProfileManagerGetProfileManager200Response();

    /**
     * Model tests for ProfileManagerGetProfileManager200Response
     */
    @Test
    public void testProfileManagerGetProfileManager200Response() {
        // TODO: test ProfileManagerGetProfileManager200Response
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'shortBio'
     */
    @Test
    public void shortBioTest() {
        // TODO: test shortBio
    }

    /**
     * Test the property 'bio'
     */
    @Test
    public void bioTest() {
        // TODO: test bio
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'heroImage'
     */
    @Test
    public void heroImageTest() {
        // TODO: test heroImage
    }

    /**
     * Test the property 'did'
     */
    @Test
    public void didTest() {
        // TODO: test did
    }

}
