include classpath("application.conf")
node-address { protocol = http, host = localhost, port = 9324, context-path = "" }
queues {
  inbox-dlq { defaultVisibilityTimeout = 180 seconds }
  inbox {
    defaultVisibilityTimeout = 1800 seconds
    deadLettersQueue { name = "inbox-dlq", maxReceiveCount = 5 }
  }
}
