#############################################
##  Configuration for Netlify deployments  ##
#############################################

[build.environment]
BUN_VERSION = "1.3.14"
BUN_FLAGS = "--ignore-scripts"
SKIP_DIDKIT_NAPI = "1"

# Global Context Default
[build]
command = "bunx nx build 1-basic-launchpad-app"
publish = "dist/"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
