/*
 * LearnCloud Network API
 * API for interacting with LearnCloud Network
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf;
import org.openapitools.client.model.BoostSendBoostRequestCredentialAnyOfEvidenceAnyOfType;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-20T20:56:53.196489431Z[Etc/UTC]", comments = "Generator version: 7.14.0-SNAPSHOT")
public class BoostSendBoostRequestCredentialAnyOfEvidence extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(BoostSendBoostRequestCredentialAnyOfEvidence.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!BoostSendBoostRequestCredentialAnyOfEvidence.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'BoostSendBoostRequestCredentialAnyOfEvidence' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf> adapterBoostSendBoostRequestCredentialAnyOfEvidenceAnyOf = gson.getDelegateAdapter(this, TypeToken.get(BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf.class));

            final Type typeInstanceListBoostSendBoostRequestCredentialAnyOfEvidenceAnyOf = new TypeToken<List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>>(){}.getType();
            final TypeAdapter<List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>> adapterListBoostSendBoostRequestCredentialAnyOfEvidenceAnyOf = (TypeAdapter<List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListBoostSendBoostRequestCredentialAnyOfEvidenceAnyOf));

            return (TypeAdapter<T>) new TypeAdapter<BoostSendBoostRequestCredentialAnyOfEvidence>() {
                @Override
                public void write(JsonWriter out, BoostSendBoostRequestCredentialAnyOfEvidence value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf`
                    if (value.getActualInstance() instanceof BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf) {
                        JsonElement element = adapterBoostSendBoostRequestCredentialAnyOfEvidenceAnyOf.toJsonTree((BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>`
                    if (value.getActualInstance() instanceof List<?>) {
                        List<?> list = (List<?>) value.getActualInstance();
                        if (list.get(0) instanceof BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf) {
                            JsonArray array = adapterListBoostSendBoostRequestCredentialAnyOfEvidenceAnyOf.toJsonTree((List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>)value.getActualInstance()).getAsJsonArray();
                            elementAdapter.write(out, array);
                            return;
                        }
                    }
                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf, List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>");
                }

                @Override
                public BoostSendBoostRequestCredentialAnyOfEvidence read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterBoostSendBoostRequestCredentialAnyOfEvidenceAnyOf;
                        BoostSendBoostRequestCredentialAnyOfEvidence ret = new BoostSendBoostRequestCredentialAnyOfEvidence();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf'", e);
                    }
                    // deserialize List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>
                    try {
                        // validate the JSON object to see if any exception is thrown
                        if (!jsonElement.isJsonArray()) {
                            throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
                        }

                        JsonArray array = jsonElement.getAsJsonArray();
                        // validate array items
                        for(JsonElement element : array) {
                            BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf.validateJsonElement(element);
                        }
                        actualAdapter = adapterListBoostSendBoostRequestCredentialAnyOfEvidenceAnyOf;
                        BoostSendBoostRequestCredentialAnyOfEvidence ret = new BoostSendBoostRequestCredentialAnyOfEvidence();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf> failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>'", e);
                    }

                    throw new IOException(String.format("Failed deserialization for BoostSendBoostRequestCredentialAnyOfEvidence: no class matches result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public BoostSendBoostRequestCredentialAnyOfEvidence() {
        super("anyOf", Boolean.FALSE);
    }

    public BoostSendBoostRequestCredentialAnyOfEvidence(Object o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf", BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf.class);
        schemas.put("List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>", List.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return BoostSendBoostRequestCredentialAnyOfEvidence.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf, List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>
     *
     * It could be an instance of the 'anyOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof List<?>) {
            List<?> list = (List<?>) instance;
            if (list.get(0) instanceof BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf) {
                super.setActualInstance(instance);
                return;
            }
        }

        throw new RuntimeException("Invalid instance type. Must be BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf, List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>");
    }

    /**
     * Get the actual instance, which can be the following:
     * BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf, List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>
     *
     * @return The actual instance (BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf, List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf`. If the actual instance is not `BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf`
     * @throws ClassCastException if the instance is not `BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf`
     */
    public BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf getBoostSendBoostRequestCredentialAnyOfEvidenceAnyOf() throws ClassCastException {
        return (BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>`. If the actual instance is not `List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>`
     * @throws ClassCastException if the instance is not `List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>`
     */
    public List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf> getListBoostSendBoostRequestCredentialAnyOfEvidenceAnyOf() throws ClassCastException {
        return (List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to BoostSendBoostRequestCredentialAnyOfEvidence
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate anyOf schemas one by one
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf
        try {
            BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>
        try {
            if (!jsonElement.isJsonArray()) {
                throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
            }
            JsonArray array = jsonElement.getAsJsonArray();
            // validate array items
            for(JsonElement element : array) {
                BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf.validateJsonElement(element);
            }
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf> failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        throw new IOException(String.format("The JSON string is invalid for BoostSendBoostRequestCredentialAnyOfEvidence with anyOf schemas: BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf, List<BoostSendBoostRequestCredentialAnyOfEvidenceAnyOf>. no class match the result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
    }

    /**
     * Create an instance of BoostSendBoostRequestCredentialAnyOfEvidence given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of BoostSendBoostRequestCredentialAnyOfEvidence
     * @throws IOException if the JSON string is invalid with respect to BoostSendBoostRequestCredentialAnyOfEvidence
     */
    public static BoostSendBoostRequestCredentialAnyOfEvidence fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, BoostSendBoostRequestCredentialAnyOfEvidence.class);
    }

    /**
     * Convert an instance of BoostSendBoostRequestCredentialAnyOfEvidence to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

