/*
 * LearnCloud Network API
 * API for interacting with LearnCloud Network
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * BoostGetBoostsRequestQueryStatusAnyOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-13T19:25:17.190189972Z[Etc/UTC]", comments = "Generator version: 7.14.0-SNAPSHOT")
public class BoostGetBoostsRequestQueryStatusAnyOf {
  /**
   * Gets or Sets $in
   */
  @JsonAdapter(InEnum.Adapter.class)
  public enum InEnum {
    DRAFT("DRAFT"),
    
    LIVE("LIVE");

    private String value;

    InEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static InEnum fromValue(String value) {
      for (InEnum b : InEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<InEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final InEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public InEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return InEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      InEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_$_IN = "$in";
  @SerializedName(SERIALIZED_NAME_$_IN)
  @javax.annotation.Nonnull
  private List<InEnum> $in = new ArrayList<>();

  public BoostGetBoostsRequestQueryStatusAnyOf() {
  }

  public BoostGetBoostsRequestQueryStatusAnyOf $in(@javax.annotation.Nonnull List<InEnum> $in) {
    this.$in = $in;
    return this;
  }

  public BoostGetBoostsRequestQueryStatusAnyOf add$InItem(InEnum $inItem) {
    if (this.$in == null) {
      this.$in = new ArrayList<>();
    }
    this.$in.add($inItem);
    return this;
  }

  /**
   * Get $in
   * @return $in
   */
  @javax.annotation.Nonnull
  public List<InEnum> get$In() {
    return $in;
  }

  public void set$In(@javax.annotation.Nonnull List<InEnum> $in) {
    this.$in = $in;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BoostGetBoostsRequestQueryStatusAnyOf boostGetBoostsRequestQueryStatusAnyOf = (BoostGetBoostsRequestQueryStatusAnyOf) o;
    return Objects.equals(this.$in, boostGetBoostsRequestQueryStatusAnyOf.$in);
  }

  @Override
  public int hashCode() {
    return Objects.hash($in);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BoostGetBoostsRequestQueryStatusAnyOf {\n");
    sb.append("    $in: ").append(toIndentedString($in)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("$in"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("$in"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BoostGetBoostsRequestQueryStatusAnyOf
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BoostGetBoostsRequestQueryStatusAnyOf.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BoostGetBoostsRequestQueryStatusAnyOf is not found in the empty JSON string", BoostGetBoostsRequestQueryStatusAnyOf.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BoostGetBoostsRequestQueryStatusAnyOf.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BoostGetBoostsRequestQueryStatusAnyOf` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BoostGetBoostsRequestQueryStatusAnyOf.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the required json array is present
      if (jsonObj.get("$in") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("$in").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `$in` to be an array in the JSON string but got `%s`", jsonObj.get("$in").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BoostGetBoostsRequestQueryStatusAnyOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BoostGetBoostsRequestQueryStatusAnyOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BoostGetBoostsRequestQueryStatusAnyOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BoostGetBoostsRequestQueryStatusAnyOf.class));

       return (TypeAdapter<T>) new TypeAdapter<BoostGetBoostsRequestQueryStatusAnyOf>() {
           @Override
           public void write(JsonWriter out, BoostGetBoostsRequestQueryStatusAnyOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BoostGetBoostsRequestQueryStatusAnyOf read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BoostGetBoostsRequestQueryStatusAnyOf given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BoostGetBoostsRequestQueryStatusAnyOf
   * @throws IOException if the JSON string is invalid with respect to BoostGetBoostsRequestQueryStatusAnyOf
   */
  public static BoostGetBoostsRequestQueryStatusAnyOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BoostGetBoostsRequestQueryStatusAnyOf.class);
  }

  /**
   * Convert an instance of BoostGetBoostsRequestQueryStatusAnyOf to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

