/*
 * LearnCloud Network API
 * API for interacting with LearnCloud Network
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import org.openapitools.client.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-13T19:25:17.190189972Z[Etc/UTC]", comments = "Generator version: 7.14.0-SNAPSHOT")
public class BoostSendBoostRequestCredentialAnyOfCredentialSchema extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(BoostSendBoostRequestCredentialAnyOfCredentialSchema.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!BoostSendBoostRequestCredentialAnyOfCredentialSchema.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'BoostSendBoostRequestCredentialAnyOfCredentialSchema' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf> adapterBoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf = gson.getDelegateAdapter(this, TypeToken.get(BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf.class));

            final Type typeInstanceListBoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf = new TypeToken<List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>>(){}.getType();
            final TypeAdapter<List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>> adapterListBoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf = (TypeAdapter<List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>>) gson.getDelegateAdapter(this, TypeToken.get(typeInstanceListBoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf));

            return (TypeAdapter<T>) new TypeAdapter<BoostSendBoostRequestCredentialAnyOfCredentialSchema>() {
                @Override
                public void write(JsonWriter out, BoostSendBoostRequestCredentialAnyOfCredentialSchema value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf`
                    if (value.getActualInstance() instanceof BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf) {
                        JsonElement element = adapterBoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf.toJsonTree((BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>`
                    if (value.getActualInstance() instanceof List<?>) {
                        List<?> list = (List<?>) value.getActualInstance();
                        if (list.get(0) instanceof BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf) {
                            JsonArray array = adapterListBoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf.toJsonTree((List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>)value.getActualInstance()).getAsJsonArray();
                            elementAdapter.write(out, array);
                            return;
                        }
                    }
                    throw new IOException("Failed to serialize as the type doesn't match anyOf schemas: BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf, List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>");
                }

                @Override
                public BoostSendBoostRequestCredentialAnyOfCredentialSchema read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterBoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf;
                        BoostSendBoostRequestCredentialAnyOfCredentialSchema ret = new BoostSendBoostRequestCredentialAnyOfCredentialSchema();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf'", e);
                    }
                    // deserialize List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>
                    try {
                        // validate the JSON object to see if any exception is thrown
                        if (!jsonElement.isJsonArray()) {
                            throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
                        }

                        JsonArray array = jsonElement.getAsJsonArray();
                        // validate array items
                        for(JsonElement element : array) {
                            BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf.validateJsonElement(element);
                        }
                        actualAdapter = adapterListBoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf;
                        BoostSendBoostRequestCredentialAnyOfCredentialSchema ret = new BoostSendBoostRequestCredentialAnyOfCredentialSchema();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf> failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>'", e);
                    }

                    throw new IOException(String.format("Failed deserialization for BoostSendBoostRequestCredentialAnyOfCredentialSchema: no class matches result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public BoostSendBoostRequestCredentialAnyOfCredentialSchema() {
        super("anyOf", Boolean.FALSE);
    }

    public BoostSendBoostRequestCredentialAnyOfCredentialSchema(Object o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf", BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf.class);
        schemas.put("List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>", List.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return BoostSendBoostRequestCredentialAnyOfCredentialSchema.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf, List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>
     *
     * It could be an instance of the 'anyOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof List<?>) {
            List<?> list = (List<?>) instance;
            if (list.get(0) instanceof BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf) {
                super.setActualInstance(instance);
                return;
            }
        }

        throw new RuntimeException("Invalid instance type. Must be BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf, List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>");
    }

    /**
     * Get the actual instance, which can be the following:
     * BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf, List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>
     *
     * @return The actual instance (BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf, List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf`. If the actual instance is not `BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf`
     * @throws ClassCastException if the instance is not `BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf`
     */
    public BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf getBoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf() throws ClassCastException {
        return (BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>`. If the actual instance is not `List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>`
     * @throws ClassCastException if the instance is not `List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>`
     */
    public List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf> getListBoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf() throws ClassCastException {
        return (List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to BoostSendBoostRequestCredentialAnyOfCredentialSchema
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate anyOf schemas one by one
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf
        try {
            BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf.validateJsonElement(jsonElement);
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>
        try {
            if (!jsonElement.isJsonArray()) {
                throw new IllegalArgumentException(String.format("Expected json element to be a array type in the JSON string but got `%s`", jsonElement.toString()));
            }
            JsonArray array = jsonElement.getAsJsonArray();
            // validate array items
            for(JsonElement element : array) {
                BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf.validateJsonElement(element);
            }
            return;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf> failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        throw new IOException(String.format("The JSON string is invalid for BoostSendBoostRequestCredentialAnyOfCredentialSchema with anyOf schemas: BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf, List<BoostSendBoostRequestCredentialAnyOfCredentialSchemaAnyOf>. no class match the result, expected at least 1. Detailed failure message for anyOf schemas: %s. JSON: %s", errorMessages, jsonElement.toString()));
    }

    /**
     * Create an instance of BoostSendBoostRequestCredentialAnyOfCredentialSchema given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of BoostSendBoostRequestCredentialAnyOfCredentialSchema
     * @throws IOException if the JSON string is invalid with respect to BoostSendBoostRequestCredentialAnyOfCredentialSchema
     */
    public static BoostSendBoostRequestCredentialAnyOfCredentialSchema fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, BoostSendBoostRequestCredentialAnyOfCredentialSchema.class);
    }

    /**
     * Convert an instance of BoostSendBoostRequestCredentialAnyOfCredentialSchema to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

