/*
 * LearnCloud Network API
 * API for interacting with LearnCloud Network
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.ContractsGetConsentedDataForContractRequestQueryCredentials;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ContractsGetConsentedContractsRequestQueryWrite
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-20T20:56:53.196489431Z[Etc/UTC]", comments = "Generator version: 7.14.0-SNAPSHOT")
public class ContractsGetConsentedContractsRequestQueryWrite {
  public static final String SERIALIZED_NAME_CREDENTIALS = "credentials";
  @SerializedName(SERIALIZED_NAME_CREDENTIALS)
  @javax.annotation.Nullable
  private ContractsGetConsentedDataForContractRequestQueryCredentials credentials;

  public static final String SERIALIZED_NAME_PERSONAL = "personal";
  @SerializedName(SERIALIZED_NAME_PERSONAL)
  @javax.annotation.Nullable
  private Map<String, Boolean> personal = new HashMap<>();

  public ContractsGetConsentedContractsRequestQueryWrite() {
  }

  public ContractsGetConsentedContractsRequestQueryWrite credentials(@javax.annotation.Nullable ContractsGetConsentedDataForContractRequestQueryCredentials credentials) {
    this.credentials = credentials;
    return this;
  }

  /**
   * Get credentials
   * @return credentials
   */
  @javax.annotation.Nullable
  public ContractsGetConsentedDataForContractRequestQueryCredentials getCredentials() {
    return credentials;
  }

  public void setCredentials(@javax.annotation.Nullable ContractsGetConsentedDataForContractRequestQueryCredentials credentials) {
    this.credentials = credentials;
  }


  public ContractsGetConsentedContractsRequestQueryWrite personal(@javax.annotation.Nullable Map<String, Boolean> personal) {
    this.personal = personal;
    return this;
  }

  public ContractsGetConsentedContractsRequestQueryWrite putPersonalItem(String key, Boolean personalItem) {
    if (this.personal == null) {
      this.personal = new HashMap<>();
    }
    this.personal.put(key, personalItem);
    return this;
  }

  /**
   * Get personal
   * @return personal
   */
  @javax.annotation.Nullable
  public Map<String, Boolean> getPersonal() {
    return personal;
  }

  public void setPersonal(@javax.annotation.Nullable Map<String, Boolean> personal) {
    this.personal = personal;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractsGetConsentedContractsRequestQueryWrite contractsGetConsentedContractsRequestQueryWrite = (ContractsGetConsentedContractsRequestQueryWrite) o;
    return Objects.equals(this.credentials, contractsGetConsentedContractsRequestQueryWrite.credentials) &&
        Objects.equals(this.personal, contractsGetConsentedContractsRequestQueryWrite.personal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(credentials, personal);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractsGetConsentedContractsRequestQueryWrite {\n");
    sb.append("    credentials: ").append(toIndentedString(credentials)).append("\n");
    sb.append("    personal: ").append(toIndentedString(personal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("credentials", "personal"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ContractsGetConsentedContractsRequestQueryWrite
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ContractsGetConsentedContractsRequestQueryWrite.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ContractsGetConsentedContractsRequestQueryWrite is not found in the empty JSON string", ContractsGetConsentedContractsRequestQueryWrite.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ContractsGetConsentedContractsRequestQueryWrite.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ContractsGetConsentedContractsRequestQueryWrite` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `credentials`
      if (jsonObj.get("credentials") != null && !jsonObj.get("credentials").isJsonNull()) {
        ContractsGetConsentedDataForContractRequestQueryCredentials.validateJsonElement(jsonObj.get("credentials"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ContractsGetConsentedContractsRequestQueryWrite.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ContractsGetConsentedContractsRequestQueryWrite' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ContractsGetConsentedContractsRequestQueryWrite> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ContractsGetConsentedContractsRequestQueryWrite.class));

       return (TypeAdapter<T>) new TypeAdapter<ContractsGetConsentedContractsRequestQueryWrite>() {
           @Override
           public void write(JsonWriter out, ContractsGetConsentedContractsRequestQueryWrite value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ContractsGetConsentedContractsRequestQueryWrite read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ContractsGetConsentedContractsRequestQueryWrite given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ContractsGetConsentedContractsRequestQueryWrite
   * @throws IOException if the JSON string is invalid with respect to ContractsGetConsentedContractsRequestQueryWrite
   */
  public static ContractsGetConsentedContractsRequestQueryWrite fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ContractsGetConsentedContractsRequestQueryWrite.class);
  }

  /**
   * Convert an instance of ContractsGetConsentedContractsRequestQueryWrite to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

