import { LaunchPadAppListItem, LaunchPadAppType } from 'learn-card-base';

export const comingSoonAiApps: LaunchPadAppListItem[] = [
    {
        id: 1,
        name: 'Future FQ',
        description: 'Future Skills Development',
        img: 'https://cdn.filestackcontent.com/pPhPx47UTq6Mf3JGKwLg',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.LEARNING],
    },
    {
        id: 2,
        name: 'Learning FQ',
        description: 'AI Storytelling & Engagement',
        img: 'https://cdn.filestackcontent.com/FUV8jB5CSCSmPqDR6Jkb',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.AI, LaunchPadAppType.LEARNING],
    },
];

export const comingSoonGameApps: LaunchPadAppListItem[] = [
    {
        id: 1,
        name: 'k-ID',
        description: 'AI Tools for Digital Parenting',
        img: 'https://cdn.filestackcontent.com/pi3ttppSVuaBaWp4AxmU',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.AI, LaunchPadAppType.GAME],
    },
    {
        id: 2,
        name: 'Roblox',
        description: 'Create & Play Games',
        img: 'https://cdn.filestackcontent.com/c46YtxpQSgKRAqFiL7Er',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.GAME],
    },
    {
        id: 3,
        name: 'Filament Games',
        description: 'Skill-building Games',
        img: 'https://cdn.filestackcontent.com/jsuaGTVnQUqYGs3z4OMj',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.GAME],
    },
    {
        id: 4,
        name: 'Nurture',
        description: 'Life Skills Games',
        img: 'https://cdn.filestackcontent.com/x62icD3iR4aPts1zeB69',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.GAME],
    },
];

export const comingSoonIntegrations: LaunchPadAppListItem[] = [
    {
        id: 0,
        name: 'ScoutPass',
        description: 'Tools for World Scouting',
        img: 'https://cdn.filestackcontent.com/NP4O97LLS7qNB1NKHGNK',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.INTEGRATION],
    },
    {
        id: 1,
        name: 'VetPass',
        description: 'Tools for Military Veterans',
        img: 'https://cdn.filestackcontent.com/R0ll6yXaS7rbxxk4MVJw',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.INTEGRATION],
    },
    {
        id: 2,
        name: 'ThinkHuman',
        description: 'Learn Skills While Watching TV',
        img: 'https://cdn.filestackcontent.com/GCmn9JwhTsyVBCEVlDmc',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.LEARNING],
    },
    {
        id: 3,
        name: 'Earth Cubs',
        description: 'Climate Change Education',
        img: 'https://cdn.filestackcontent.com/R36GAZp8QhK3P3TKs4ph',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.LEARNING],
    },
    {
        id: 4,
        name: 'Pi-Top',
        description: 'STEM Skills Development',
        img: 'https://cdn.filestackcontent.com/ocDep9I3Szi5iAuFUpS9',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.LEARNING],
    },
    {
        id: 5,
        name: 'TAG',
        description: 'Youth Action for Sustainability',
        img: 'https://cdn.filestackcontent.com/upyFnoXDTkyrgsqEdHh9',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.LEARNING],
    },
    {
        id: 6,
        name: 'Scholas',
        description: `Pope Francis's Youth Movement`,
        img: 'https://cdn.filestackcontent.com/hZNHZSWSQI2TUKrhkegT',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.LEARNING],
    },
    {
        id: 7,
        name: 'Open Campus',
        description: 'Learning Financial Literacy',
        img: 'https://cdn.filestackcontent.com/tEaX4R8lQQugjPbIQTT6',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.LEARNING],
    },
    {
        id: 8,
        name: 'Guardians',
        description: 'Learning Tools for Parents',
        img: 'https://cdn.filestackcontent.com/IFZGcw8xQWuhHcUW6LPi',
        isConnected: false,
        displayInLaunchPad: true,
        comingSoon: true,
        handleConnect: () => {},
        handleView: () => {},
        appType: [LaunchPadAppType.AI, LaunchPadAppType.LEARNING, LaunchPadAppType.GAME],
    },
];
