#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../touch@3.1.0/node_modules/touch/bin/nodetouch.js" "$@"
else
  exec node  "$basedir/../../../../../touch@3.1.0/node_modules/touch/bin/nodetouch.js" "$@"
fi
