import { animals, uniqueNamesGenerator, type Config } from 'unique-names-generator';

export const adjectives = [
    'Admirable',
    'Adventurous',
    'Altruistic',
    'Amazing',
    'Assuming',
    'Audacious',
    'Aweless',
    'Benevolent',
    'Bighearted',
    'Bold',
    'Brassy',
    'Caring',
    'Celebrated',
    'Charismatic',
    'Cheeky',
    'Chivalrous',
    'Clever',
    'Commanding',
    'Compassionate',
    'Confident',
    'Considerate',
    'Courageous',
    'Daring',
    'Dashing',
    'Dauntless',
    'Dedicated',
    'Defiant',
    'Determined',
    'Dignified',
    'Disciplined',
    'Distinguished',
    'Doughty',
    'Eminent',
    'Enterprising',
    'Exalted',
    'Excellent',
    'Extraordinary',
    'Faithful',
    'Fearless',
    'Foolhardy',
    'Free',
    'Gallant',
    'Game',
    'Generous',
    'Gracious',
    'Greathearted',
    'Gritty',
    'Gutsy',
    'Hardy',
    'Herculean',
    'Hidden',
    'Honorable',
    'Humble',
    'Idealist',
    'Imprudent',
    'Ingenious',
    'Inspiring',
    'Intelligent',
    'Intrepid',
    'Kind',
    'Lionhearted',
    'Lofty',
    'Loyal',
    'Magnanimous',
    'Moral',
    'Nervy',
    'Noble',
    'Outstanding',
    'Persevering',
    'Plucky',
    'Powerful',
    'Princely',
    'Prodigious',
    'Prominent',
    'Protectors',
    'Proud',
    'Relentless',
    'Renowned',
    'Resolute',
    'Responsible',
    'Selfless',
    'Sincere',
    'Spirited',
    'Spunky',
    'Stalwart',
    'Stately',
    'Storied',
    'Stout',
    'Strong',
    'Talented',
    'Tenacious',
    'Tough',
    'Trustworthy',
    'Unabashed',
    'Unafraid',
    'Undaunted',
    'Undismayed',
    'Unfearful',
    'Unflinching',
    'Unselfish',
    'Unshakable',
    'Valiant',
    'Valorous',
    'Venturesome',
    'Virtuous',
    'Wise',
    'Witty',
    'Worthy',
];

export const DEFAULT_DID_NAME_CONFIG: Config = {
    dictionaries: [['The'], adjectives, animals],
    separator: ' ',
    length: 3,
    style: 'capital',
};

export const generateRandomUsername = () => {
    return uniqueNamesGenerator(DEFAULT_DID_NAME_CONFIG);
};