# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from openapi_client.models.boost_get_boost_recipients200_response_inner_to_any_of import BoostGetBoostRecipients200ResponseInnerToAnyOf
from openapi_client.models.boost_get_boost_recipients200_response_inner_to_any_of1 import BoostGetBoostRecipients200ResponseInnerToAnyOf1
from openapi_client.models.boost_get_boost_recipients200_response_inner_to_any_of2 import BoostGetBoostRecipients200ResponseInnerToAnyOf2
from openapi_client.models.boost_get_boost_recipients200_response_inner_to_any_of3 import BoostGetBoostRecipients200ResponseInnerToAnyOf3
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

BOOSTGETBOOSTRECIPIENTS200RESPONSEINNERTO_ANY_OF_SCHEMAS = ["BoostGetBoostRecipients200ResponseInnerToAnyOf", "BoostGetBoostRecipients200ResponseInnerToAnyOf1", "BoostGetBoostRecipients200ResponseInnerToAnyOf2", "BoostGetBoostRecipients200ResponseInnerToAnyOf3"]

class BoostGetBoostRecipients200ResponseInnerTo(BaseModel):
    """
    BoostGetBoostRecipients200ResponseInnerTo
    """

    # data type: BoostGetBoostRecipients200ResponseInnerToAnyOf
    anyof_schema_1_validator: Optional[BoostGetBoostRecipients200ResponseInnerToAnyOf] = None
    # data type: BoostGetBoostRecipients200ResponseInnerToAnyOf1
    anyof_schema_2_validator: Optional[BoostGetBoostRecipients200ResponseInnerToAnyOf1] = None
    # data type: BoostGetBoostRecipients200ResponseInnerToAnyOf2
    anyof_schema_3_validator: Optional[BoostGetBoostRecipients200ResponseInnerToAnyOf2] = None
    # data type: BoostGetBoostRecipients200ResponseInnerToAnyOf3
    anyof_schema_4_validator: Optional[BoostGetBoostRecipients200ResponseInnerToAnyOf3] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[BoostGetBoostRecipients200ResponseInnerToAnyOf, BoostGetBoostRecipients200ResponseInnerToAnyOf1, BoostGetBoostRecipients200ResponseInnerToAnyOf2, BoostGetBoostRecipients200ResponseInnerToAnyOf3]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "BoostGetBoostRecipients200ResponseInnerToAnyOf", "BoostGetBoostRecipients200ResponseInnerToAnyOf1", "BoostGetBoostRecipients200ResponseInnerToAnyOf2", "BoostGetBoostRecipients200ResponseInnerToAnyOf3" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = BoostGetBoostRecipients200ResponseInnerTo.model_construct()
        error_messages = []
        # validate data type: BoostGetBoostRecipients200ResponseInnerToAnyOf
        if not isinstance(v, BoostGetBoostRecipients200ResponseInnerToAnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BoostGetBoostRecipients200ResponseInnerToAnyOf`")
        else:
            return v

        # validate data type: BoostGetBoostRecipients200ResponseInnerToAnyOf1
        if not isinstance(v, BoostGetBoostRecipients200ResponseInnerToAnyOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BoostGetBoostRecipients200ResponseInnerToAnyOf1`")
        else:
            return v

        # validate data type: BoostGetBoostRecipients200ResponseInnerToAnyOf2
        if not isinstance(v, BoostGetBoostRecipients200ResponseInnerToAnyOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BoostGetBoostRecipients200ResponseInnerToAnyOf2`")
        else:
            return v

        # validate data type: BoostGetBoostRecipients200ResponseInnerToAnyOf3
        if not isinstance(v, BoostGetBoostRecipients200ResponseInnerToAnyOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BoostGetBoostRecipients200ResponseInnerToAnyOf3`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in BoostGetBoostRecipients200ResponseInnerTo with anyOf schemas: BoostGetBoostRecipients200ResponseInnerToAnyOf, BoostGetBoostRecipients200ResponseInnerToAnyOf1, BoostGetBoostRecipients200ResponseInnerToAnyOf2, BoostGetBoostRecipients200ResponseInnerToAnyOf3. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[BoostGetBoostRecipients200ResponseInnerToAnyOf] = None
        try:
            instance.actual_instance = BoostGetBoostRecipients200ResponseInnerToAnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[BoostGetBoostRecipients200ResponseInnerToAnyOf1] = None
        try:
            instance.actual_instance = BoostGetBoostRecipients200ResponseInnerToAnyOf1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[BoostGetBoostRecipients200ResponseInnerToAnyOf2] = None
        try:
            instance.actual_instance = BoostGetBoostRecipients200ResponseInnerToAnyOf2.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[BoostGetBoostRecipients200ResponseInnerToAnyOf3] = None
        try:
            instance.actual_instance = BoostGetBoostRecipients200ResponseInnerToAnyOf3.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into BoostGetBoostRecipients200ResponseInnerTo with anyOf schemas: BoostGetBoostRecipients200ResponseInnerToAnyOf, BoostGetBoostRecipients200ResponseInnerToAnyOf1, BoostGetBoostRecipients200ResponseInnerToAnyOf2, BoostGetBoostRecipients200ResponseInnerToAnyOf3. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], BoostGetBoostRecipients200ResponseInnerToAnyOf, BoostGetBoostRecipients200ResponseInnerToAnyOf1, BoostGetBoostRecipients200ResponseInnerToAnyOf2, BoostGetBoostRecipients200ResponseInnerToAnyOf3]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


