# coding: utf-8

"""
    LearnCloud Network API

    API for interacting with LearnCloud Network

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CredentialRefreshGetCredentialRefreshHistory200ResponseRecordsInner(BaseModel):
    """
    CredentialRefreshGetCredentialRefreshHistory200ResponseRecordsInner
    """ # noqa: E501
    version: Annotated[int, Field(le=9007199254740991, strict=True, gt=0)]
    published_at: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="publishedAt")
    effective_at: Optional[StrictStr] = Field(default=None, alias="effectiveAt")
    etag: Optional[StrictStr] = None
    signing_mode: Optional[StrictStr] = Field(default=None, alias="signingMode")
    update_summary: Optional[StrictStr] = Field(default=None, alias="updateSummary")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["version", "publishedAt", "effectiveAt", "etag", "signingMode", "updateSummary"]

    @field_validator('signing_mode')
    def signing_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['issuer-signed', 'signing-authority']):
            raise ValueError("must be one of enum values ('issuer-signed', 'signing-authority')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CredentialRefreshGetCredentialRefreshHistory200ResponseRecordsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if effective_at (nullable) is None
        # and model_fields_set contains the field
        if self.effective_at is None and "effective_at" in self.model_fields_set:
            _dict['effectiveAt'] = None

        # set to None if etag (nullable) is None
        # and model_fields_set contains the field
        if self.etag is None and "etag" in self.model_fields_set:
            _dict['etag'] = None

        # set to None if update_summary (nullable) is None
        # and model_fields_set contains the field
        if self.update_summary is None and "update_summary" in self.model_fields_set:
            _dict['updateSummary'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CredentialRefreshGetCredentialRefreshHistory200ResponseRecordsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "publishedAt": obj.get("publishedAt"),
            "effectiveAt": obj.get("effectiveAt"),
            "etag": obj.get("etag"),
            "signingMode": obj.get("signingMode"),
            "updateSummary": obj.get("updateSummary")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


