# For some reason, there are certain files that tend to just update automatically when running
# our usual scripts, resulting in an unclean git worktree that can be solved by simply committing
# the updated files. This script does that.

name: Auto-Commits

on:
  push: main

env:
  CI: true

jobs:
  auto-commits:
    name: Auto-Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Fetch main for NX comparison
        run: |
          git fetch --no-tags --prune --depth=5 origin main

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Restore nx cache
        id: restore-nx-cache
        uses: actions/cache/restore@v3
        with:
          path: .nx-cache
          key: ${{ runner.os }}-nx-cache-${{ github.workflow }}

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Commit and push changes
        run: |
          git config --global pull.rebase true
          git config --global user.name "Auto-Commit"
          git config --global user.email "beestontaylor@learningeconomy.io"
          git diff --quiet pnpm-lock.yaml || git add pnpm-lock.yaml
          git status -v
          git commit -m ":green_heart: Auto-commits" && git pull && git push || echo "Nothing to see here!"

      - name: Save nx cache
        uses: actions/cache/save@v3
        with:
          path: .nx-cache
          key: ${{ steps.restore-nx-cache.outputs.cache-primary-key }}
