name: Deploy

on:
  push:
    branches:
      - WE-2612-Add-LCN

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: us-east-1
  STAGE: production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Restore nx cache
        id: restore-nx-cache
        uses: actions/cache/restore@v3
        with:
          path: .nx-cache
          key: ${{ runner.os }}-nx-cache-${{ github.workflow }}

      - name: Install dependencies
        run: pnpm i

      - name: Run tests
        run: pnpm exec nx affected --target=test --base=HEAD~1 --head=HEAD

      - name: Get Affected List
        id: affected
        run: echo "AFFECTED=$(pnpm exec nx print-affected --base=origin/main --head=HEAD --select=projects)" >> $GITHUB_ENV

      - name: Deploy Brain Service Lambda
        if: contains(env.AFFECTED, 'network-brain-service')
        run: pnpm exec nx serverless-deploy network-brain-service

      - name: Save nx cache
        uses: actions/cache/save@v3
        with:
          path: .nx-cache
          key: ${{ steps.restore-nx-cache.outputs.cache-primary-key }}
