name: Docker Release

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  push-to-registry:
    name: Push Docker images to Docker Hub
    environment: ci-tests
    if: | 
      github.event.pull_request.merged == true &&
      github.head_ref == 'changeset-release/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Composite Setup Action
        uses: ./.github/actions/setup

      - name: Run tests
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: pnpm exec nx affected --target=test --base=HEAD~1 --head=HEAD
        env:
          SEED: ${{ secrets.SEED }}
          LEARN_CLOUD_SEED: ${{ secrets.LEARN_CLOUD_SEED }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get Brain Service package version
        id: brain-service-version
        working-directory: "./services/learn-card-network/brain-service"        
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Extract metadata for Brain Service
        id: brain-service-meta
        uses: docker/metadata-action@v5
        with:
          images: welibrary/lcn-brain-service
          tags: |
            type=semver,pattern={{version}},value=v${{ steps.brain-service-version.outputs.version }}

      - name: Build and push Brain Service image
        id: push-brain-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./services/learn-card-network/brain-service/Dockerfile
          push: true
          tags: ${{ steps.brain-service-meta.outputs.tags }}
          labels: ${{ steps.brain-service-meta.outputs.labels }}

      - name: Get LearnCloud Service package version
        id: cloud-service-version
        working-directory: "./services/learn-card-network/learn-cloud-service"        
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Extract metadata for Cloud Service
        id: cloud-service-meta
        uses: docker/metadata-action@v5
        with:
          images: welibrary/lcn-cloud-service
          tags: |
            type=semver,pattern={{version}},value=v${{ steps.cloud-service-version.outputs.version }}

      - name: Build and push Cloud Service image
        id: push-cloud-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./services/learn-card-network/learn-cloud-service/Dockerfile
          push: true
          tags: ${{ steps.cloud-service-meta.outputs.tags }}
          labels: ${{ steps.cloud-service-meta.outputs.labels }}
